import {
  BRANCH_INACTIVE,
  DECISION_LAYOUT as L,
  EDGE_LABELS,
  NOT_TAKEN,
  decisionEdges,
  type DecisionMap,
  type IntelligenceContent,
  type KnowledgeNetwork,
  type MasteryProfile,
} from './intelligenceTypes'

export * from './intelligenceTypes'

const batchMap: DecisionMap = {
  id: 'dm-batch',
  title: { fa: 'ترخیص بچ BATCH-2418 پس از مردودی کیفی', en: 'BATCH-2418 release after a quality rejection' },
  version: 'v2.4',
  asOf: { fa: 'اجرای جاری · ۱۸ مرداد، ۰۹:۳۰', en: 'Current run • 9 Aug, 09:30' },
  focusNodeId: 'bt-oven',
  nodes: [
    {
      id: 'bt-start',
      ...L.start,
      verdict: 'neutral',
      label: { fa: 'درخواست ترخیص بچ BATCH-2418', en: 'Release request for BATCH-2418' },
      meta: { fa: 'سفارش SO-3092 · لنت دیسکی', en: 'Order SO-3092 • disc pads' },
      rule: { fa: 'هر بچ پس از سومین مردودی ۳۰ روز اخیر وارد مسیر ترخیص کنترل‌شده می‌شود.', en: 'After the third rejection in 30 days, every batch enters the controlled release route.' },
      actual: { fa: 'سه بچ مردود در ۳۰ روز', en: 'Three rejected batches in 30 days' },
      result: { fa: 'مسیر باز شد', en: 'Route opened' },
      confidence: 'high',
      sources: [
        { fa: 'برگه‌های کنترل کیفیت', en: 'QC certificates' },
        { fa: 'برنامه تولید', en: 'Production plan' },
      ],
      changes: { fa: 'با کمتر از سه مردودی، بچ در مسیر ترخیص عادی می‌ماند.', en: 'With fewer than three rejections the batch stays in the normal release route.' },
      updated: { fa: '۰۸:۱۰', en: '08:10' },
      recordType: 'inventory',
      recordId: 'inv-fg-8842',
      workId: 'work-qc-1',
    },
    {
      id: 'bt-friction',
      ...L.c1,
      verdict: 'pass',
      label: { fa: 'ضریب اصطکاک در پنجره است؟', en: 'Is the friction coefficient in window?' },
      meta: { fa: 'μ در محدوده · عبور', en: 'μ within range • PASS' },
      rule: { fa: 'ضریب اصطکاک بچ باید در پنجره استاندارد محصول بماند.', en: 'Batch friction coefficient must stay inside the product standard window.' },
      actual: { fa: 'نتیجه آزمون در محدوده مجاز', en: 'Test result within the allowed band' },
      result: { fa: 'در پنجره', en: 'In window' },
      confidence: 'high',
      sources: [
        { fa: 'برگه QC-541', en: 'QC certificate QC-541' },
        { fa: 'آزمون اصطکاک', en: 'Friction test bench' },
      ],
      changes: { fa: 'خروج ضریب اصطکاک از پنجره، بچ را مستقیم به قرنطینه می‌برد.', en: 'A friction coefficient outside the window sends the batch straight to quarantine.' },
      updated: { fa: '۰۸:۱۵', en: '08:15' },
      recordType: 'inventory',
      recordId: 'inv-fg-8842',
      workId: 'work-qc-1',
    },
    {
      id: 'bt-quarantine',
      ...L.t1,
      verdict: 'neutral',
      label: { fa: 'قرنطینه کامل بچ', en: 'Full batch quarantine' },
      rule: { fa: 'بچ خارج از پنجره اصطکاک ترخیص نمی‌شود.', en: 'A batch outside the friction window is not released.' },
      actual: NOT_TAKEN,
      result: BRANCH_INACTIVE,
      confidence: 'medium',
      sources: [{ fa: 'رویه کنترل کیفیت', en: 'QC procedure' }],
      changes: { fa: 'مردودی آزمون اصطکاک این شاخه را فعال می‌کند.', en: 'A failed friction test activates this branch.' },
      updated: { fa: '۰۸:۱۵', en: '08:15' },
      recordType: 'inventory',
      recordId: 'inv-fg-8842',
    },
    {
      id: 'bt-material',
      ...L.c2,
      verdict: 'pass',
      label: { fa: 'ماده اصطکاکی از لات تاییدشده است؟', en: 'Is friction material from an approved lot?' },
      meta: { fa: 'رزین SP-1068 · عبور', en: 'Resin SP-1068 • PASS' },
      rule: { fa: 'ماده اصطکاکی هر بچ باید از لات دارای گواهی تامین‌کننده باشد.', en: 'Friction material for each batch must come from a supplier-certified lot.' },
      actual: { fa: 'رزین فنولیک SP-1068 با گواهی لات', en: 'Phenolic resin SP-1068 with lot certificate' },
      result: { fa: 'تاییدشده', en: 'Approved' },
      confidence: 'medium',
      sources: [
        { fa: 'انبار مواد', en: 'Material warehouse' },
        { fa: 'گواهی تامین‌کننده', en: 'Supplier certificate' },
      ],
      changes: { fa: 'مصرف لات بدون گواهی، بچ را به بازآزمون مواد می‌برد.', en: 'Using an uncertified lot routes the batch to material retesting.' },
      updated: { fa: '۰۸:۳۰', en: '08:30' },
      recordType: 'inventory',
      recordId: 'inv-oil-10w40',
      workId: 'work-wh-1',
    },
    {
      id: 'bt-retest',
      ...L.t2,
      verdict: 'neutral',
      label: { fa: 'بازآزمون مواد اولیه', en: 'Retest raw material' },
      rule: { fa: 'لات بدون گواهی پیش از ترخیص بازآزمون می‌شود.', en: 'An uncertified lot is retested before release.' },
      actual: NOT_TAKEN,
      result: BRANCH_INACTIVE,
      confidence: 'medium',
      sources: [{ fa: 'آزمایشگاه مواد', en: 'Material lab' }],
      changes: { fa: 'مصرف لات بدون گواهی این شاخه را فعال می‌کند.', en: 'Consuming an uncertified lot activates this branch.' },
      updated: { fa: '۰۸:۳۰', en: '08:30' },
      recordType: 'inventory',
      recordId: 'inv-oil-10w40',
    },
    {
      id: 'bt-oven',
      ...L.c3,
      verdict: 'fail',
      label: { fa: 'پروفیل دمای کوره پخت درست بوده؟', en: 'Was the curing oven profile correct?' },
      meta: { fa: '۱۲ درجه پایین‌تر · مردود', en: '12 degrees low • FAIL' },
      rule: { fa: 'دمای ناحیه دوم کوره پخت نباید بیش از ۵ درجه از نقطه تنظیم فاصله بگیرد.', en: 'Zone-two curing temperature must not deviate more than 5 degrees from setpoint.' },
      actual: { fa: '۱۲ درجه پایین‌تر از نقطه تنظیم', en: '12 degrees below setpoint' },
      result: { fa: 'مردود', en: 'Failed' },
      confidence: 'medium',
      sources: [
        { fa: 'لاگ دمای کوره پخت', en: 'Curing oven temperature log' },
        { fa: 'برگه‌های QC-549 و QC-0241', en: 'QC certificates QC-549 and QC-0241' },
        { fa: 'گزارش کالیبراسیون', en: 'Calibration report' },
      ],
      changes: { fa: 'با کالیبراسیون ترموکوپل ناحیه دوم و بازپخت، مسیر به ترخیص عادی بچ تغییر می‌کند.', en: 'Calibrating the zone-two thermocouple and re-curing reroutes this to normal batch release.' },
      updated: { fa: '۰۹:۳۰', en: '09:30' },
      recordType: 'transaction',
      recordId: 'TX-468',
      workId: 'work-qc-1',
    },
    {
      id: 'bt-release',
      ...L.t3,
      verdict: 'neutral',
      label: { fa: 'ترخیص عادی بچ', en: 'Normal batch release' },
      rule: { fa: 'بچ با پروفیل پخت سالم بدون اقدام اضافه ترخیص می‌شود.', en: 'A batch with a healthy curing profile is released with no extra action.' },
      actual: NOT_TAKEN,
      result: BRANCH_INACTIVE,
      confidence: 'high',
      sources: [{ fa: 'رویه کنترل کیفیت', en: 'QC procedure' }],
      changes: { fa: 'اصلاح پروفیل دما این شاخه را فعال می‌کند.', en: 'Correcting the temperature profile activates this branch.' },
      updated: { fa: '۰۹:۳۰', en: '09:30' },
      recordType: 'inventory',
      recordId: 'inv-fg-8842',
    },
    {
      id: 'bt-hold',
      ...L.cond,
      verdict: 'conditional',
      label: { fa: 'توقف ترخیص بازه پخت مشکوک؟', en: 'Hold releases from the suspect curing window?' },
      meta: { fa: 'مشروط به تایید نگهداری', en: 'CONDITIONAL on maintenance sign-off' },
      rule: { fa: 'توقف ترخیص گروهی نیازمند تایید کنترل کیفیت و نگهداری است.', en: 'A group release hold requires QC and maintenance sign-off.' },
      actual: { fa: 'در انتظار تایید BR-MNT-442', en: 'Awaiting BR-MNT-442 approval' },
      result: { fa: 'مشروط', en: 'Conditional' },
      confidence: 'medium',
      sources: [
        { fa: 'عامل کنترل کیفیت', en: 'Quality control agent' },
        { fa: 'عامل نگهداری', en: 'Maintenance agent' },
      ],
      changes: { fa: 'تایید هزینه نگهداری BR-MNT-442 امروز، کالیبراسیون را در همین شیفت ممکن می‌کند.', en: 'Approving maintenance cost BR-MNT-442 today makes calibration possible within this shift.' },
      updated: { fa: '۰۹:۳۰', en: '09:30' },
      recordType: 'transaction',
      recordId: 'BR-MNT-442',
      workId: 'work-maint-1',
    },
    {
      id: 'bt-ship',
      ...L.t4,
      verdict: 'neutral',
      label: { fa: 'ارسال بدون بازآزمون', en: 'Ship without retesting' },
      rule: { fa: 'بدون توقف، بچ‌های بازه مشکوک ارسال می‌شوند.', en: 'Without a hold, batches from the suspect window ship.' },
      actual: { fa: 'در صورت عدم تایید', en: 'If not approved' },
      result: { fa: 'پیامد منفی', en: 'Negative consequence' },
      confidence: 'high',
      sources: [{ fa: 'مکاتبه مشتری OEM', en: 'OEM customer correspondence' }],
      changes: { fa: 'تایید توقف، ریسک اقدام اصلاحی مشتری را حذف می‌کند.', en: 'Approving the hold removes the customer corrective-action risk.' },
      updated: { fa: '۰۹:۳۰', en: '09:30' },
      recordType: 'correspondence',
      recordId: 'BR-CORR-412',
    },
    {
      id: 'bt-outcome',
      ...L.outcome,
      verdict: 'outcome',
      label: { fa: 'کالیبراسیون ترموکوپل و بازآزمون بازه پخت', en: 'Calibrate the thermocouple and retest the curing window' },
      meta: { fa: 'هدف: مردودی زیر ۲٪', en: 'Target: rejection under 2%' },
      rule: { fa: 'تصمیم مجاز باید مالک، مهلت و روش راستی‌آزمایی داشته باشد.', en: 'An authorized decision must carry an owner, a deadline, and a verification method.' },
      actual: { fa: 'مالک: مهندس آریا · راستی‌آزمایی: برگه QC بچ بعدی', en: 'Owner: Eng. Arya • Verification: next batch QC certificate' },
      result: { fa: 'آماده اجرا', en: 'Ready to execute' },
      confidence: 'high',
      sources: [
        { fa: 'کار کنترل کیفیت', en: 'Quality control work' },
        { fa: 'کارتابل تایید', en: 'Approval queue' },
      ],
      changes: { fa: 'اگر کالیبراسیون تا شیفت شب انجام نشود، نتیجه به بازپخت کامل بچ‌های بازه تغییر می‌کند.', en: 'If calibration slips past the night shift, the outcome changes to a full re-cure of the window batches.' },
      updated: { fa: '۰۹:۳۰', en: '09:30' },
      recordType: 'transaction',
      recordId: 'BR-MNT-442',
      workId: 'work-qc-1',
    },
  ],
  edges: decisionEdges(
    { start: 'bt-start', c1: 'bt-friction', t1: 'bt-quarantine', c2: 'bt-material', t2: 'bt-retest', c3: 'bt-oven', t3: 'bt-release', cond: 'bt-hold', t4: 'bt-ship', outcome: 'bt-outcome' },
    EDGE_LABELS,
  ),
  trace: ['bt-start', 'bt-friction', 'bt-material', 'bt-oven', 'bt-hold', 'bt-outcome'],
  simulation: {
    title: { fa: 'اگر توقف ترخیص بازه پخت تایید نشود', en: 'If the curing-window release hold is not approved' },
    body: {
      fa: 'بچ‌های پخت‌شده در بازه دمای پایین بدون بازآزمون ارسال می‌شوند و الگوی سه مردودی ۳۰ روز ادامه پیدا می‌کند.',
      en: 'Batches cured in the low-temperature window ship without retesting and the three-rejection pattern continues.',
    },
    consequence: {
      fa: 'پیامد: ادامه حدود ۷۴ میلیون تومان ضایعات ماهانه و درخواست گزارش اقدام اصلاحی دوم از مشتری OEM.',
      en: 'Consequence: roughly 74 million toman of monthly scrap continues and the OEM customer issues a second corrective-action request.',
    },
    to: '/work/work-qc-1',
  },
  history: [
    { at: { fa: '۰۹:۳۰ امروز', en: '09:30 today' }, text: { fa: 'نسخه v2.4 با آستانه انحراف دمای ۵ درجه اجرا شد.', en: 'Version v2.4 ran with the 5-degree temperature deviation threshold.' } },
    { at: { fa: '۱۶ مرداد', en: '7 Aug' }, text: { fa: 'شرط گواهی لات ماده اصطکاکی به مسیر اضافه شد.', en: 'The friction-material lot certificate check was added to the route.' } },
    { at: { fa: '۰۳ مرداد', en: '25 Jul' }, text: { fa: 'نسخه v2.3: پنجره شمارش مردودی از ۱۴ به ۳۰ روز رسید.', en: 'Version v2.3: the rejection counting window moved from 14 to 30 days.' } },
  ],
}

const pressMap: DecisionMap = {
  id: 'dm-press',
  title: { fa: 'تصمیم توقف پرس هیدرولیک ۲', en: 'Hydraulic press 2 stoppage decision' },
  version: 'v1.8',
  asOf: { fa: 'اجرای جاری · ۱۸ مرداد، ۰۸:۴۰', en: 'Current run • 9 Aug, 08:40' },
  focusNodeId: 'pr-capacity',
  nodes: [
    {
      id: 'pr-start',
      ...L.start,
      verdict: 'neutral',
      label: { fa: 'توقف پرس هیدرولیک ۲', en: 'Hydraulic press 2 stoppage' },
      meta: { fa: 'BR-MNT-442 · ۳۲۰ میلیون تومان', en: 'BR-MNT-442 • 320 million toman' },
      rule: { fa: 'هر توقف بالای دو ساعت روی خط پرس وارد مسیر تصمیم نگهداری می‌شود.', en: 'Any press-line stoppage over two hours enters the maintenance decision route.' },
      actual: { fa: 'توقف از ۰۶:۴۰ گزارش شده', en: 'Stoppage reported from 06:40' },
      result: { fa: 'مسیر باز شد', en: 'Route opened' },
      confidence: 'high',
      sources: [
        { fa: 'گزارش توقف خط', en: 'Line stoppage report' },
        { fa: 'برنامه تولید', en: 'Production plan' },
      ],
      changes: { fa: 'توقف کوتاه‌تر از دو ساعت در نگهداری روزمره حل می‌شود.', en: 'A stoppage under two hours is handled in routine maintenance.' },
      updated: { fa: '۰۶:۴۰', en: '06:40' },
      recordType: 'transaction',
      recordId: 'BR-MNT-442',
      workId: 'work-maint-1',
    },
    {
      id: 'pr-safety',
      ...L.c1,
      verdict: 'pass',
      label: { fa: 'ایمنی اپراتور تامین است؟', en: 'Is operator safety assured?' },
      meta: { fa: 'قفل و برچسب اجرا شده · عبور', en: 'Lockout applied • PASS' },
      rule: { fa: 'هر مداخله روی پرس نیازمند اجرای کامل قفل و برچسب است.', en: 'Any press intervention requires a complete lockout-tagout.' },
      actual: { fa: 'قفل و برچسب توسط تیم نگهداری اجرا شد', en: 'Lockout-tagout applied by the maintenance team' },
      result: { fa: 'ایمن', en: 'Safe' },
      confidence: 'high',
      sources: [{ fa: 'چک‌لیست ایمنی', en: 'Safety checklist' }],
      changes: { fa: 'نقص قفل و برچسب، کار را تا رفع ایراد متوقف می‌کند.', en: 'A lockout gap halts the work until it is fixed.' },
      updated: { fa: '۰۶:۵۰', en: '06:50' },
      recordType: 'transaction',
      recordId: 'BR-MNT-442',
    },
    {
      id: 'pr-stopwork',
      ...L.t1,
      verdict: 'neutral',
      label: { fa: 'توقف کار تا رفع ایراد ایمنی', en: 'Stop work until the safety gap is closed' },
      rule: { fa: 'بدون ایمنی کامل، مداخله انجام نمی‌شود.', en: 'Without full safety, no intervention proceeds.' },
      actual: NOT_TAKEN,
      result: BRANCH_INACTIVE,
      confidence: 'medium',
      sources: [{ fa: 'چک‌لیست ایمنی', en: 'Safety checklist' }],
      changes: { fa: 'ثبت ایراد ایمنی این شاخه را فعال می‌کند.', en: 'Logging a safety gap activates this branch.' },
      updated: { fa: '۰۶:۵۰', en: '06:50' },
      recordType: 'transaction',
      recordId: 'BR-MNT-442',
    },
    {
      id: 'pr-part',
      ...L.c2,
      verdict: 'pass',
      label: { fa: 'قطعه یدکی در دسترس است؟', en: 'Is the spare part available?' },
      meta: { fa: 'قالب T-118 در سفارش · عبور', en: 'Die T-118 on order • PASS' },
      rule: { fa: 'تعمیر تنها با قطعه موجود یا قابل تحویل در همان روز آغاز می‌شود.', en: 'Repair only starts with a part in stock or deliverable the same day.' },
      actual: { fa: 'قطعه موجود · قالب یدکی PR-196 در جریان', en: 'Part in stock • spare die PR-196 in progress' },
      result: { fa: 'در دسترس', en: 'Available' },
      confidence: 'medium',
      sources: [
        { fa: 'انبار قطعات', en: 'Spare parts store' },
        { fa: 'درخواست خرید PR-196', en: 'Purchase request PR-196' },
      ],
      changes: { fa: 'نبود قطعه، تعمیر را به مسیر تامین اضطراری منتقل می‌کند.', en: 'A missing part moves the repair to the emergency sourcing route.' },
      updated: { fa: '۰۷:۲۰', en: '07:20' },
      recordType: 'purchase',
      recordId: 'PR-196',
      workId: 'work-maint-1',
    },
    {
      id: 'pr-source',
      ...L.t2,
      verdict: 'neutral',
      label: { fa: 'تامین اضطراری قطعه', en: 'Emergency part sourcing' },
      rule: { fa: 'بدون قطعه، تامین اضطراری آغاز می‌شود.', en: 'Without a part, emergency sourcing starts.' },
      actual: NOT_TAKEN,
      result: BRANCH_INACTIVE,
      confidence: 'medium',
      sources: [{ fa: 'تدارکات مواد', en: 'Materials procurement' }],
      changes: { fa: 'کمبود قطعه این شاخه را فعال می‌کند.', en: 'A part shortage activates this branch.' },
      updated: { fa: '۰۷:۲۰', en: '07:20' },
      recordType: 'purchase',
      recordId: 'PR-196',
    },
    {
      id: 'pr-capacity',
      ...L.c3,
      verdict: 'fail',
      label: { fa: 'ظرفیت جایگزین کافی است؟', en: 'Is alternative capacity sufficient?' },
      meta: { fa: 'پرس ۱ فقط ۷۰٪ · مردود', en: 'Press 1 at 70% only • FAIL' },
      rule: { fa: 'ظرفیت جایگزین باید حداقل ۹۰٪ برنامه شیفت را پوشش دهد.', en: 'Alternative capacity must cover at least 90% of the shift plan.' },
      actual: { fa: 'پرس ۱ تنها ۷۰٪ برنامه را پوشش می‌دهد', en: 'Press 1 covers only 70% of the plan' },
      result: { fa: 'مردود', en: 'Failed' },
      confidence: 'medium',
      sources: [
        { fa: 'برنامه بچ BATCH-2418', en: 'Batch plan BATCH-2418' },
        { fa: 'گزارش ظرفیت پرس ۱', en: 'Press 1 capacity report' },
        { fa: 'تعهد سفارش SO-3092', en: 'Order commitment SO-3092' },
      ],
      changes: { fa: 'با افزودن شیفت شب روی پرس ۱، پوشش به ۹۲٪ می‌رسد و مسیر به تولید جایگزین تغییر می‌کند.', en: 'Adding a night shift on press 1 lifts coverage to 92% and reroutes this to alternative production.' },
      updated: { fa: '۰۸:۴۰', en: '08:40' },
      recordType: 'inventory',
      recordId: 'inv-fg-8842',
      workId: 'work-plan-1',
    },
    {
      id: 'pr-alt',
      ...L.t3,
      verdict: 'neutral',
      label: { fa: 'ادامه تولید روی پرس ۱', en: 'Continue production on press 1' },
      rule: { fa: 'ظرفیت کافی جایگزین، نیاز به تعمیر فوری را حذف می‌کند.', en: 'Sufficient alternative capacity removes the need for an urgent repair.' },
      actual: NOT_TAKEN,
      result: BRANCH_INACTIVE,
      confidence: 'high',
      sources: [{ fa: 'برنامه تولید', en: 'Production plan' }],
      changes: { fa: 'افزایش ظرفیت پرس ۱ این شاخه را فعال می‌کند.', en: 'Increasing press 1 capacity activates this branch.' },
      updated: { fa: '۰۸:۴۰', en: '08:40' },
      recordType: 'inventory',
      recordId: 'inv-fg-8842',
    },
    {
      id: 'pr-urgent',
      ...L.cond,
      verdict: 'conditional',
      label: { fa: 'تایید نگهداری اضطراری تا ۱۰:۰۰؟', en: 'Emergency maintenance approved by 10:00?' },
      meta: { fa: 'مشروط به تایید مدیر کارخانه', en: 'CONDITIONAL on plant manager sign-off' },
      rule: { fa: 'هزینه نگهداری بالای ۲۵۰ میلیون تومان نیازمند تایید مدیر کارخانه است.', en: 'Maintenance cost above 250 million toman requires plant manager sign-off.' },
      actual: { fa: 'در انتظار تصمیم مدیر کارخانه', en: 'Awaiting plant manager decision' },
      result: { fa: 'مشروط', en: 'Conditional' },
      confidence: 'medium',
      sources: [
        { fa: 'گفتگوی تایید BR-MNT-442', en: 'BR-MNT-442 approval thread' },
        { fa: 'پیمانکار نگهداری', en: 'Maintenance contractor' },
      ],
      changes: { fa: 'اگر پیمانکار شیفت عصر را بپذیرد، مهلت تصمیم تا ۱۳:۰۰ عقب می‌رود.', en: 'If the contractor accepts the evening shift, the decision deadline moves to 13:00.' },
      updated: { fa: '۰۸:۴۰', en: '08:40' },
      recordType: 'transaction',
      recordId: 'BR-MNT-442',
      workId: 'work-maint-1',
    },
    {
      id: 'pr-late',
      ...L.t4,
      verdict: 'neutral',
      label: { fa: 'تاخیر تحویل SO-3092', en: 'Late delivery on SO-3092' },
      rule: { fa: 'بدون تعمیر، کسری تولید به تعهد تحویل می‌رسد.', en: 'Without the repair, the output gap reaches the delivery commitment.' },
      actual: { fa: 'در صورت عدم تایید', en: 'If not approved' },
      result: { fa: 'پیامد منفی', en: 'Negative consequence' },
      confidence: 'high',
      sources: [{ fa: 'تعهد سفارش SO-3092', en: 'Order commitment SO-3092' }],
      changes: { fa: 'تایید تا ۱۰:۰۰ این پیامد را حذف می‌کند.', en: 'Approval by 10:00 removes this consequence.' },
      updated: { fa: '۰۸:۴۰', en: '08:40' },
      recordType: 'inventory',
      recordId: 'inv-fg-8842',
    },
    {
      id: 'pr-outcome',
      ...L.outcome,
      verdict: 'outcome',
      label: { fa: 'تایید BR-MNT-442 و انتقال بچ اولویت‌دار به پرس ۱', en: 'Approve BR-MNT-442 and move the priority batch to press 1' },
      meta: { fa: '۳۲۰ میلیون تومان · تایید مدیر کارخانه', en: '320 million toman • plant manager approval' },
      rule: { fa: 'تصمیم مجاز باید مالک، مهلت و روش راستی‌آزمایی داشته باشد.', en: 'An authorized decision must carry an owner, a deadline, and a verification method.' },
      actual: { fa: 'مالک: مهندس آریا · راستی‌آزمایی: راه‌اندازی پرس تا شیفت عصر', en: 'Owner: Eng. Arya • Verification: press restart by the evening shift' },
      result: { fa: 'آماده اجرا', en: 'Ready to execute' },
      confidence: 'high',
      sources: [
        { fa: 'کارتابل تایید', en: 'Approval queue' },
        { fa: 'کار نگهداری پرس', en: 'Press maintenance work' },
      ],
      changes: { fa: 'اگر قطعه تا ظهر نرسد، نتیجه به تولید جزئی و مذاکره تاریخ تحویل SO-3092 تغییر می‌کند.', en: 'If the part misses noon, the outcome changes to partial output and renegotiating the SO-3092 date.' },
      updated: { fa: '۰۸:۴۰', en: '08:40' },
      recordType: 'transaction',
      recordId: 'BR-MNT-442',
      workId: 'work-maint-1',
    },
  ],
  edges: decisionEdges(
    { start: 'pr-start', c1: 'pr-safety', t1: 'pr-stopwork', c2: 'pr-part', t2: 'pr-source', c3: 'pr-capacity', t3: 'pr-alt', cond: 'pr-urgent', t4: 'pr-late', outcome: 'pr-outcome' },
    EDGE_LABELS,
  ),
  trace: ['pr-start', 'pr-safety', 'pr-part', 'pr-capacity', 'pr-urgent', 'pr-outcome'],
  simulation: {
    title: { fa: 'اگر نگهداری اضطراری تا ۱۰:۰۰ تایید نشود', en: 'If emergency maintenance is not approved by 10:00' },
    body: {
      fa: 'با ادامه توقف تا شیفت شب، کسری تولید به ۵٫۶ هزار جفت می‌رسد و ظرفیت پرس ۱ تنها ۷۰٪ برنامه را پوشش می‌دهد.',
      en: 'With the stoppage running into the night shift the output gap reaches 5.6 thousand pairs while press 1 covers only 70% of plan.',
    },
    consequence: {
      fa: 'پیامد: SO-3092 در تاریخ تعهدشده تحویل نمی‌شود و نرخ تحویل به‌موقع زیر هدف ۹۵٪ می‌رود.',
      en: 'Consequence: SO-3092 misses its committed date and on-time delivery falls below the 95% target.',
    },
    to: '/work/work-maint-1',
  },
  history: [
    { at: { fa: '۰۸:۴۰ امروز', en: '08:40 today' }, text: { fa: 'نسخه v1.8 با آستانه پوشش ظرفیت ۹۰٪ اجرا شد.', en: 'Version v1.8 ran with the 90% capacity coverage threshold.' } },
    { at: { fa: '۱۵ مرداد', en: '6 Aug' }, text: { fa: 'شرط در دسترس بودن قطعه یدکی به مسیر اضافه شد.', en: 'The spare-part availability check was added to the route.' } },
    { at: { fa: '۰۱ مرداد', en: '23 Jul' }, text: { fa: 'نسخه v1.7: سقف تایید نگهداری به ۲۵۰ میلیون تومان تغییر کرد.', en: 'Version v1.7: the maintenance approval ceiling moved to 250 million toman.' } },
  ],
}

const knowledge: KnowledgeNetwork = {
  centerId: 'k-cure-window',
  nodes: [
    {
      id: 'k-cure-window',
      kind: 'fact',
      label: { fa: 'انحراف دمای ناحیه دوم کوره پخت', en: 'Zone-two curing temperature deviation' },
      value: { fa: '۱۲ درجه', en: '12 degrees' },
      statement: { fa: 'هر سه بچ مردود ۳۰ روز اخیر در بازه‌ای پخت شده‌اند که دمای ناحیه دوم ۱۲ درجه پایین‌تر از نقطه تنظیم بوده است.', en: 'All three rejected batches in the last 30 days were cured while zone-two temperature ran 12 degrees below setpoint.' },
      domain: { fa: 'کنترل کیفیت', en: 'Quality control' },
      currency: { fa: 'جاری', en: 'Current' },
      confidence: 'high',
      sources: [
        { fa: 'لاگ دمای کوره پخت', en: 'Curing oven temperature log' },
        { fa: 'برگه‌های QC-541 و QC-549', en: 'QC certificates QC-541 and QC-549' },
        { fa: 'مصاحبه سرپرست کیفیت', en: 'Quality supervisor interview' },
      ],
      relationships: 7,
      usedInDecisions: 3,
      updated: { fa: '۱۸ مرداد، ۰۹:۳۰', en: '9 Aug, 09:30' },
      x: 420,
      y: 210,
      to: '/records/inventory/inv-fg-8842',
    },
    {
      id: 'k-qc-sheets',
      kind: 'evidence',
      label: { fa: 'برگه‌های کنترل کیفیت بچ‌های مردود', en: 'QC certificates of rejected batches' },
      relation: { fa: 'شواهد آن', en: 'evidenced by' },
      statement: { fa: 'برگه‌های QC-541، QC-549 و QC-0241 زمان و پارامترهای پخت هر بچ مردود را ثبت کرده‌اند.', en: 'Certificates QC-541, QC-549 and QC-0241 record the curing time and parameters of each rejected batch.' },
      domain: { fa: 'کنترل کیفیت', en: 'Quality control' },
      currency: { fa: 'جاری', en: 'Current' },
      confidence: 'high',
      sources: [{ fa: 'آزمایشگاه کیفیت', en: 'Quality lab' }],
      relationships: 3,
      usedInDecisions: 2,
      updated: { fa: '۱۸ مرداد، ۰۸:۱۵', en: '9 Aug, 08:15' },
      x: 60,
      y: 90,
      to: '/records/transaction/TX-468',
    },
    {
      id: 'k-release-policy',
      kind: 'policy',
      label: { fa: 'سیاست ترخیص کنترل‌شده بچ', en: 'Controlled batch release policy' },
      relation: { fa: 'حاکم بر آن', en: 'governed by' },
      statement: { fa: 'پس از سومین مردودی در ۳۰ روز، ترخیص بچ‌های همان بازه تولید نیازمند بازآزمون است.', en: 'After a third rejection in 30 days, releasing batches from the same production window requires retesting.' },
      domain: { fa: 'حکمرانی کیفیت', en: 'Quality governance' },
      currency: { fa: 'مصوب', en: 'Approved' },
      confidence: 'high',
      sources: [
        { fa: 'رویه کنترل کیفیت', en: 'QC procedure' },
        { fa: 'الزام مشتری OEM', en: 'OEM customer requirement' },
      ],
      relationships: 5,
      usedInDecisions: 4,
      updated: { fa: '۱۲ مرداد', en: '3 Aug' },
      x: 360,
      y: -30,
      to: '/map?tab=authority',
    },
    {
      id: 'k-qc-team',
      kind: 'owner',
      label: { fa: 'تیم کنترل کیفیت', en: 'Quality control team' },
      relation: { fa: 'مالک', en: 'owned by' },
      statement: { fa: 'عامل کنترل کیفیت مالک بازآزمون، ترخیص و گزارش اقدام اصلاحی است.', en: 'The quality control agent owns retesting, release, and corrective-action reporting.' },
      domain: { fa: 'کنترل کیفیت', en: 'Quality control' },
      currency: { fa: 'جاری', en: 'Current' },
      confidence: 'high',
      sources: [{ fa: 'نقشه عملیاتی کارخانه', en: 'Plant operating map' }],
      relationships: 4,
      usedInDecisions: 2,
      updated: { fa: '۱۸ مرداد، ۰۸:۲۰', en: '9 Aug, 08:20' },
      x: 760,
      y: 80,
      to: '/agents?agent=agent-agri',
    },
    {
      id: 'k-reject-target',
      kind: 'target',
      label: { fa: 'هدف مردودی زیر ۲٪', en: 'Rejection target under 2%' },
      relation: { fa: 'مقایسه با', en: 'compared with' },
      statement: { fa: 'هدف اعلام‌شده کارخانه، نگه‌داشتن نرخ مردودی بچ زیر ۲ درصد است.', en: 'The declared plant target is to keep batch rejection below 2 percent.' },
      domain: { fa: 'اهداف تولید', en: 'Production goals' },
      currency: { fa: 'اعلام‌شده', en: 'Declared' },
      confidence: 'medium',
      sources: [{ fa: 'برنامه فصلی کارخانه', en: 'Plant quarterly plan' }],
      relationships: 3,
      usedInDecisions: 2,
      updated: { fa: '۱۰ مرداد', en: '1 Aug' },
      x: 20,
      y: 260,
      to: '/plan',
    },
    {
      id: 'k-scrap-cost',
      kind: 'outcome',
      label: { fa: 'هزینه ضایعات ماهانه', en: 'Monthly scrap cost' },
      relation: { fa: 'اثر بر', en: 'affects' },
      statement: { fa: 'هر بچ مردود حدود ۷۴ میلیون تومان ضایعات و بازکاری به بهای تمام‌شده اضافه می‌کند.', en: 'Each rejected batch adds roughly 74 million toman of scrap and rework to cost of goods.' },
      domain: { fa: 'مالی', en: 'Finance' },
      currency: { fa: 'جاری', en: 'Current' },
      confidence: 'medium',
      sources: [
        { fa: 'دفتر مالی', en: 'Finance ledger' },
        { fa: 'تراکنش TX-468', en: 'Transaction TX-468' },
      ],
      relationships: 4,
      usedInDecisions: 3,
      updated: { fa: '۱۸ مرداد، ۰۸:۳۰', en: '9 Aug, 08:30' },
      x: 800,
      y: 250,
      to: '/records/transaction/TX-468',
    },
    {
      id: 'k-oven-pattern',
      kind: 'pattern',
      label: { fa: 'افت دمای کوره، مردودی می‌سازد', en: 'Oven temperature drops create rejections' },
      relation: { fa: 'پشتیبانی می‌کند', en: 'supports' },
      statement: { fa: 'در بچ‌های تولیدشده در ناحیه سالم کوره، ضریب اصطکاک پایدار مانده و مردودی ثبت نشده است.', en: 'Batches cured in the healthy oven zone kept a stable friction coefficient with no rejections.' },
      domain: { fa: 'الگوهای تولید', en: 'Production patterns' },
      currency: { fa: 'اعتبارسنجی‌شده', en: 'Validated' },
      confidence: 'medium',
      sources: [
        { fa: 'لاگ دمای کوره پخت', en: 'Curing oven temperature log' },
        { fa: 'آزمون اصطکاک', en: 'Friction test bench' },
      ],
      relationships: 5,
      usedInDecisions: 3,
      updated: { fa: '۱۷ مرداد', en: '8 Aug' },
      x: 700,
      y: 420,
      to: '/records/inventory/inv-fg-8842',
    },
    {
      id: 'k-supply-stability',
      kind: 'initiative',
      label: { fa: 'پایداری تامین مواد اصطکاکی', en: 'Friction material supply stability' },
      relation: { fa: 'محدود می‌کند', en: 'constrains' },
      statement: { fa: 'اقدام فعال برای افزایش نقطه سفارش به ۴۵ کیسه و بستن قرارداد تامین ماهانه.', en: 'An active initiative to raise the reorder point to 45 sacks and sign a monthly supply contract.' },
      domain: { fa: 'برنامه', en: 'Plan' },
      currency: { fa: 'فعال', en: 'Active' },
      confidence: 'medium',
      sources: [{ fa: 'درخواست خرید BR-MR-184', en: 'Purchase request BR-MR-184' }],
      relationships: 3,
      usedInDecisions: 1,
      updated: { fa: '۱۵ مرداد', en: '6 Aug' },
      x: 120,
      y: 420,
      to: '/records/purchase/BR-MR-184',
    },
    {
      id: 'k-resin-stock',
      kind: 'evidence',
      label: { fa: 'رزین SP-1068 با ۱۴ کیسه موجودی', en: 'Resin SP-1068 at 14 sacks' },
      relation: { fa: 'شواهد ریسک', en: 'evidence of risk' },
      statement: { fa: 'موجودی رزین فنولیک به ۱۴ کیسه رسیده و با مصرف ۶ کیسه در روز حدود ۲٫۳ روز دوام دارد.', en: 'Phenolic resin stock is at 14 sacks and, at 6 sacks per day, lasts about 2.3 days.' },
      domain: { fa: 'تدارکات مواد', en: 'Materials procurement' },
      currency: { fa: 'جاری', en: 'Current' },
      confidence: 'high',
      sources: [{ fa: 'انبار مواد', en: 'Material warehouse' }],
      relationships: 2,
      usedInDecisions: 2,
      updated: { fa: '۱۸ مرداد، ۰۸:۱۲', en: '9 Aug, 08:12' },
      outerRing: true,
      x: -240,
      y: 400,
      to: '/records/inventory/inv-oil-10w40',
    },
    {
      id: 'k-oem-request',
      kind: 'outcome',
      label: { fa: 'درخواست اقدام اصلاحی مشتری OEM', en: 'OEM corrective-action request' },
      relation: { fa: 'پیامد تجاری', en: 'commercial consequence' },
      statement: { fa: 'مشتری OEM گزارش ۸D و مستندات ترخیص بچ‌های بعدی را درخواست کرده است.', en: 'The OEM customer has requested an 8D report and release documentation for subsequent batches.' },
      domain: { fa: 'فروش و مکاتبات', en: 'Sales and correspondence' },
      currency: { fa: 'جاری', en: 'Current' },
      confidence: 'high',
      sources: [{ fa: 'مکاتبه BR-CORR-412', en: 'Correspondence BR-CORR-412' }],
      relationships: 2,
      usedInDecisions: 2,
      updated: { fa: '۱۸ مرداد، ۰۸:۰۰', en: '9 Aug, 08:00' },
      outerRing: true,
      x: 1080,
      y: 400,
      to: '/records/correspondence/BR-CORR-412',
    },
    {
      id: 'k-otd-target',
      kind: 'target',
      label: { fa: 'هدف تحویل به‌موقع ۹۵٪', en: 'On-time delivery target 95%' },
      relation: { fa: 'آستانه', en: 'threshold of' },
      statement: { fa: 'هدف کارخانه، تحویل به‌موقع بالای ۹۵ درصد سفارش‌ها است.', en: 'The plant target is on-time delivery above 95 percent of orders.' },
      domain: { fa: 'فروش و سفارش‌ها', en: 'Sales and orders' },
      currency: { fa: 'اعلام‌شده', en: 'Declared' },
      confidence: 'medium',
      sources: [{ fa: 'برنامه فصلی کارخانه', en: 'Plant quarterly plan' }],
      relationships: 3,
      usedInDecisions: 1,
      updated: { fa: '۱۶ مرداد', en: '7 Aug' },
      outerRing: true,
      x: 1080,
      y: 80,
      to: '/plan',
    },
  ],
  history: [
    { at: { fa: '۱۸ مرداد، ۰۹:۳۰', en: '9 Aug, 09:30' }, text: { fa: 'انحراف دمای ناحیه دوم از ۸ به ۱۲ درجه اصلاح شد.', en: 'Zone-two deviation corrected from 8 to 12 degrees.' } },
    { at: { fa: '۱۷ مرداد', en: '8 Aug' }, text: { fa: 'الگوی «افت دمای کوره، مردودی می‌سازد» اعتبارسنجی شد.', en: 'The “oven temperature drops create rejections” pattern was validated.' } },
    { at: { fa: '۱۲ مرداد', en: '3 Aug' }, text: { fa: 'سیاست ترخیص کنترل‌شده بچ به‌عنوان دانش مصوب ثبت شد.', en: 'The controlled batch release policy was recorded as approved knowledge.' } },
  ],
}

const mastery: MasteryProfile = {
  explanation: {
    fa: 'درک تثبیت‌شده استیو با واقعیت اعتبارسنجی‌شده خط تولید و نیت مجاز مدیریت کارخانه در این دامنه مقایسه شده است.',
    en: "Steve's frozen understanding was matched against validated line reality and authorized plant intent for this scope.",
  },
  reviews: [
    { id: 'rev-mordad', label: { fa: 'بازبینی مرداد ۱۴۰۵', en: 'August 2026 review' }, asOf: { fa: '۳۱ مرداد ۱۴۰۵', en: '31 Aug 2026' }, frozenAt: { fa: '۱۸:۰۰', en: '18:00' } },
    { id: 'rev-tir', label: { fa: 'بازبینی تیر ۱۴۰۵', en: 'July 2026 review' }, asOf: { fa: '۳۱ تیر ۱۴۰۵', en: '31 Jul 2026' }, frozenAt: { fa: '۱۷:۳۰', en: '17:30' } },
  ],
  attention: [
    {
      id: 'ma-health',
      kind: 'health',
      title: { fa: '۲ فرض کهنه درباره پارامترهای پخت نیازمند اعتبارسنجی', en: '2 stale premises on curing parameters need validation' },
      detail: { fa: 'منابع جاری در دسترس · ۱ تعارض بین لاگ کوره و برگه کنترل کیفیت', en: 'Current sources available • 1 conflict between the oven log and the QC certificate' },
      action: { fa: 'بررسی سلامت', en: 'Review health' },
      to: '/map?tab=systems',
    },
    {
      id: 'ma-review',
      kind: 'review',
      title: { fa: 'شواهد و مصاحبه‌ها · ۷ از ۱۰ کامل', en: 'Evidence and interviews • 7 of 10 complete' },
      detail: { fa: 'مهلت ۲۲ مرداد · این بازبینی می‌سنجد استیو پیش از بازبینی چه می‌دانست.', en: 'Due 13 Aug • This review measures what Steve knew before the review.' },
      action: { fa: 'ادامه بازبینی', en: 'Continue review' },
      to: '/work',
    },
    {
      id: 'ma-gap',
      kind: 'gap',
      title: { fa: 'استثناهای ترخیص بچ پس از مردودی', en: 'Post-rejection batch release exceptions' },
      detail: { fa: 'بر تصمیم ترخیص BATCH-2418 و پیش‌بینی هزینه ضایعات اثر می‌گذارد', en: 'Affects the BATCH-2418 release decision and the scrap cost forecast' },
      action: { fa: 'باز کردن شکاف', en: 'Open gap' },
      to: '/records/inventory/inv-fg-8842',
    },
  ],
  history: [
    { at: { fa: '۳۱ مرداد ۱۴۰۵', en: '31 Aug 2026' }, text: { fa: 'نتیجه تسلط دامنه کارخانه تثبیت شد.', en: 'Plant-scope mastery result was frozen.' } },
    { at: { fa: '۱۵ مرداد', en: '6 Aug' }, text: { fa: 'شکاف تسلط «ترخیص بچ پس از مردودی» باز شد.', en: 'The “post-rejection batch release” mastery gap was opened.' } },
    { at: { fa: '۳۱ تیر ۱۴۰۵', en: '31 Jul 2026' }, text: { fa: 'شاخص تسلط دوره قبل با اعتبار ارزیابی «بالا» بسته شد.', en: 'The previous mastery index closed with “high” assessment reliability.' } },
  ],
  fullResultTo: '/agents?agent=agent-exec',
}

export const intelligenceContent: IntelligenceContent = {
  decisionMaps: [batchMap, pressMap],
  knowledge,
  mastery,
}
