import type { DemoState } from './types'

const now = '۰۹:۴۲'

export const initialState: DemoState = {
  toast: null,
  brief: {
    dateLabel: 'شنبه ۱۸ مرداد ۱۴۰۵',
    greeting: 'صبح بخیر، مهندس آرش آریا',
    paragraphs: [
      'خط تولید امروز با یک پرس متوقف کار می‌کند: پرس هیدرولیک ۲ از ۰۶:۴۰ به دلیل نشتی خوابیده و هزینه نگهداری آن (تراکنش BR-MNT-442) در صف مالی است. خرید اضطراری ماده اصطکاکی (درخواست BR-MR-184) هم هنوز در انتظار تایید شماست، در حالی که موجودی رزین فنولیک SP-1068 زیر نقطه سفارش رفته است.',
      'بچ BATCH-2417 در آزمون ضریب اصطکاک مردود و با برگه QC-0241 قرنطینه شد؛ با کسری ۶۴۰ جفت FG-8842، تعهد تحویل سفارش SO-3092 به قطعه‌گستر پارس بدون آزادسازی دستور تولید PROD-1148 محقق نمی‌شود. نامه مشتری ۴۱۲/ک هم بی‌پاسخ مانده است.',
      'تا ظهر باید تایید BR-MR-184، تعیین تکلیف BATCH-2417 و راه‌اندازی مجدد پرس ۲ روشن شوند تا جلسه برنامه‌ریزی تولید ۱۰:۰۰ و کمیته کیفیت ۱۲:۳۰ بر مبنای وضعیت واقعی خط تصمیم بگیرند.',
    ],
    lines: [
      { label: 'از آخرین بازبینی', text: 'بچ BATCH-2418 وارد کوره پخت شد؛ BR-MR-184 و BR-MNT-442 در صف تایید ماندند.' },
      { label: 'هنوز باز', text: 'قرنطینه بچ BATCH-2417، توقف پرس ۲، و نامه مشتری بی‌پاسخ.' },
      { label: 'تمرکز امروز', text: 'رفع بلاکر پرس ۲ و آزادسازی PROD-1148 پیش از جلسه ۱۰:۰۰.' },
      { label: 'الان آماده شوید', text: 'جلسه برنامه‌ریزی تولید ۱۰:۰۰ و کمیته کیفیت ۱۲:۳۰.' },
    ],
  },
  fuelSeries: [
    { day: '۱۲', benzine: 10.4, gasoil: 3.6 },
    { day: '۱۳', benzine: 11.1, gasoil: 4.1 },
    { day: '۱۴', benzine: 9.8, gasoil: 3.2 },
    { day: '۱۵', benzine: 11.9, gasoil: 4.4 },
    { day: '۱۶', benzine: 12.3, gasoil: 4.8 },
    { day: '۱۷', benzine: 10.7, gasoil: 3.9 },
    { day: '۱۸', benzine: 11.6, gasoil: 4.2 },
  ],
  visualFeeds: [
    {
      id: 'vf-press',
      title: 'خط پرس هیدرولیک',
      location: 'سالن تولید',
      src: '/media/brake-press-line.png',
      status: 'attention',
      time: '۰۹:۳۵',
      unitId: 'unit-hr',
      recordType: 'work',
      recordId: 'work-maint-1',
      alertId: 'alert-press-stop',
    },
    {
      id: 'vf-qc',
      title: 'میز بازرسی کیفیت',
      location: 'واحد QC',
      src: '/media/brake-qc-bench.png',
      status: 'attention',
      time: '۰۹:۲۰',
      unitId: 'unit-agri',
      recordType: 'work',
      recordId: 'work-qc-1',
      alertId: 'alert-qc-556',
    },
    {
      id: 'vf-fg',
      title: 'انبار محصول نهایی',
      location: 'انبار FG',
      src: '/media/brake-fg-warehouse.png',
      status: 'live',
      time: '۰۹:۴۰',
      unitId: 'unit-wh',
      recordType: 'inventory',
      recordId: 'inv-fg-8842',
    },
  ],
  units: [
    {
      id: 'unit-holding',
      name: 'مدیریت کارخانه آریاترمز',
      kind: 'مرکز فرماندهی',
      owner: 'مهندس آرش آریا',
      agentId: 'agent-exec',
      status: 'info',
      kpiLabel: 'واحدهای تحت نظارت',
      kpiValue: '۹',
      summary: 'نظارت یکپارچه بر برنامه‌ریزی، تولید، کیفیت، تامین، انبار، فروش و مالی کارخانه.',
    },
    {
      id: 'unit-fuel',
      name: 'تولید و پرس',
      kind: 'خط تولید',
      owner: 'سرپرست خط پرس',
      agentId: 'agent-fuel',
      status: 'warning',
      kpiLabel: 'تولید دیروز',
      kpiValue: '۱۱٫۶ هزار جفت',
      alert: 'پرس ۲ از ۰۶:۴۰ متوقف است',
      summary: 'اختلاط، پرس گرم، پخت و پرداخت لنت روی دو خط پرس هیدرولیک ۴۰۰ تن.',
    },
    {
      id: 'unit-plan',
      name: 'برنامه‌ریزی تولید',
      kind: 'برنامه‌ریزی',
      owner: 'کارشناس برنامه‌ریزی',
      agentId: 'agent-plan',
      status: 'warning',
      kpiLabel: 'دستور تولید باز',
      kpiValue: '۶',
      alert: 'PROD-1148 به دلیل توقف پرس عقب افتاد',
      summary: 'ترجمه سفارش فروش به دستور تولید، توالی بچ‌ها و تعادل ظرفیت پرس و کوره پخت.',
    },
    {
      id: 'unit-agri',
      name: 'کنترل کیفیت',
      kind: 'کیفیت',
      owner: 'مسئول آزمایشگاه',
      agentId: 'agent-agri',
      status: 'danger',
      kpiLabel: 'نرخ مردودی بچ',
      kpiValue: '۳٫۱٪',
      alert: 'بچ BATCH-2417 در آزمون اصطکاک مردود شد',
      summary: 'آزمون ضریب اصطکاک، برش، ضخامت و NVH روی نمونه هر بچ پیش از ترخیص محصول.',
    },
    {
      id: 'unit-proc',
      name: 'تدارکات مواد',
      kind: 'تامین',
      owner: 'کارشناس تدارکات',
      agentId: 'agent-proc',
      status: 'danger',
      kpiLabel: 'درخواست باز',
      kpiValue: '۳',
      alert: 'ماده اصطکاکی زیر نقطه سفارش',
      summary: 'تامین رزین، الیاف، پرکننده معدنی و ورق پشتی از تامین‌کنندگان تاییدشده.',
    },
    {
      id: 'unit-hr',
      name: 'نگهداری و تعمیرات',
      kind: 'نگهداری',
      owner: 'سرپرست نت',
      agentId: 'agent-hr',
      status: 'danger',
      kpiLabel: 'توقف باز',
      kpiValue: '۱',
      alert: 'نشتی سیستم هیدرولیک پرس ۲',
      summary: 'نگهداری پیشگیرانه و تعمیرات پرس، کوره پخت، میکسر و خط پرداخت.',
    },
    {
      id: 'unit-wh',
      name: 'انبار مواد و محصول',
      kind: 'انبارداری',
      owner: 'سرپرست انبار',
      agentId: 'agent-wh',
      status: 'danger',
      kpiLabel: 'زیر نقطه سفارش',
      kpiValue: '۵ قلم',
      alert: 'رزین فنولیک SP-1068 در آستانه اتمام',
      summary: 'موجودی مواد اولیه، ورق پشتی، اقلام بسته‌بندی و محصول نهایی آماده ارسال.',
    },
    {
      id: 'unit-re',
      name: 'فروش و سفارش‌ها',
      kind: 'فروش',
      owner: 'مدیر فروش',
      agentId: 'agent-re',
      status: 'warning',
      kpiLabel: 'سفارش باز',
      kpiValue: '۱۴',
      alert: 'SO-3092 با ریسک تاخیر تحویل',
      summary: 'سفارش‌های OEM و بازار یدکی، تعهد تحویل و هماهنگی ارسال با مشتریان.',
    },
    {
      id: 'unit-fin',
      name: 'مالی',
      kind: 'مالی',
      owner: 'مدیر مالی',
      agentId: 'agent-fin',
      status: 'warning',
      kpiLabel: 'تایید باز',
      kpiValue: '۳',
      alert: 'هزینه نگهداری پرس و خرید اضطراری در انتظار',
      summary: 'پرداخت تامین‌کنندگان، بهای تمام‌شده هر بچ و کنترل هزینه توقف خط.',
    },
    {
      id: 'unit-corr',
      name: 'مکاتبات و اسناد فنی',
      kind: 'مکاتبات',
      owner: 'دبیرخانه فنی',
      agentId: 'agent-corr',
      status: 'warning',
      kpiLabel: 'نامه معوق',
      kpiValue: '۱',
      alert: 'درخواست اقدام اصلاحی مشتری بدون پاسخ',
      summary: 'ثبت و پیگیری مکاتبات مشتریان OEM، گزارش انطباق و پرونده اقدام اصلاحی — گردش دقیق تایید هنوز قطعی نشده و در دمو به‌صورت نمونه نمایش داده می‌شود.',
    },
  ],
  inventory: [
    {
      id: 'inv-oil-10w40',
      sku: 'رزین فنولیک SP-1068 (ماده اصطکاکی)',
      warehouse: 'انبار مواد اولیه',
      onHand: 14,
      reorder: 32,
      unit: 'کیسه ۲۵ کیلویی',
      avgDailyUse: 6,
      lastUpdate: '۰۸:۱۲',
      status: 'danger',
      purchaseRequestId: 'BR-MR-184',
      workId: 'work-wh-1',
      alertId: 'alert-inv-friction',
      history: [
        { date: '۱۵ مرداد', delta: -8, note: 'شارژ میکسر برای بچ BATCH-2414' },
        { date: '۱۶ مرداد', delta: -6, note: 'شارژ میکسر برای بچ BATCH-2416' },
        { date: '۱۷ مرداد', delta: -7, note: 'بچ BATCH-2417 و اختلاط مجدد' },
        { date: '۱۸ مرداد', delta: -5, note: 'شارژ شیفت صبح بچ BATCH-2418' },
      ],
      requiredQty: 26,
      incomingQty: 60,
      incomingEta: '۱۹ مرداد',
      supplier: 'شیمی پلیمر کاوه',
      affectedOrderIds: ['PROD-1148', 'PROD-1147'],
    },
    {
      id: 'inv-fiber',
      sku: 'الیاف آرامید AR-9',
      warehouse: 'انبار مواد اولیه',
      onHand: 21,
      reorder: 24,
      unit: 'کیسه',
      avgDailyUse: 2,
      lastUpdate: '۰۸:۰۰',
      status: 'warning',
      workId: 'work-proc-1',
      history: [
        { date: '۱۶ مرداد', delta: -3, note: 'فرمول لنت دیسکی سواری' },
        { date: '۱۸ مرداد', delta: -2, note: 'شارژ بچ BATCH-2418' },
      ],
      requiredQty: 22,
      supplier: 'نساجی آرامید ایران',
    },
    {
      id: 'inv-backplate',
      sku: 'ورق پشتی فولادی BP-24',
      warehouse: 'انبار مواد اولیه',
      onHand: 4200,
      reorder: 3000,
      unit: 'عدد',
      avgDailyUse: 620,
      lastUpdate: '۰۷:۵۰',
      status: 'success',
      history: [{ date: '۱۷ مرداد', delta: -640, note: 'ورود به خط چربی‌زدایی و چسب' }],
    },
    {
      id: 'inv-powder',
      sku: 'رنگ پودری اپوکسی مشکی',
      warehouse: 'انبار مواد کمکی',
      onHand: 9,
      reorder: 12,
      unit: 'بشکه',
      avgDailyUse: 0.8,
      lastUpdate: '۰۸:۰۵',
      status: 'warning',
      purchaseRequestId: 'BR-MR-191',
      workId: 'work-wh-2',
      history: [{ date: '۱۶ مرداد', delta: -2, note: 'شارژ کابین پاشش' }],
      requiredQty: 11,
      incomingQty: 10,
      incomingEta: '۲۱ مرداد',
      supplier: 'پوشش‌های صنعتی البرز',
      affectedOrderIds: ['PROD-1145'],
    },
    {
      id: 'inv-fg-8842',
      imageSrc: '/media/brake-fg-warehouse.png',
      sku: 'محصول نهایی FG-8842 — لنت دیسکی سواری',
      warehouse: 'انبار محصول',
      onHand: 1860,
      reorder: 2500,
      unit: 'جفت',
      avgDailyUse: 540,
      lastUpdate: '۰۹:۱۰',
      status: 'warning',
      workId: 'work-re-1',
      alertId: 'alert-so-3092',
      history: [
        { date: '۱۷ مرداد', delta: 980, note: 'ترخیص QC بچ BATCH-2416' },
        { date: '۱۸ مرداد', delta: -720, note: 'بارگیری محموله SH-1207' },
      ],
    },
    {
      id: 'inv-pack',
      sku: 'کارتن و شرینک بسته‌بندی',
      warehouse: 'انبار محصول',
      onHand: 5400,
      reorder: 3500,
      unit: 'عدد',
      avgDailyUse: 480,
      lastUpdate: 'دیروز',
      status: 'success',
      history: [{ date: '۱۶ مرداد', delta: -500, note: 'بسته‌بندی سری FG-8840' }],
    },
  ],
  purchases: [
    {
      id: 'BR-MR-184',
      title: 'خرید اضطراری ماده اصطکاکی — رزین فنولیک SP-1068',
      status: 'pending',
      unitId: 'unit-proc',
      requester: 'کارشناس تدارکات',
      approver: 'مهندس آرش آریا',
      supplier: 'شیمی پلیمر کاوه',
      amount: 486000000,
      amountLabel: '۴۸۶ میلیون تومان',
      quantity: 60,
      itemId: 'inv-oil-10w40',
      reason: 'موجودی به ۱۴ کیسه رسیده؛ با مصرف میانگین ۶ کیسه در روز، اتمام تقریبی ۲٫۳ روز و توقف اختلاط بچ‌های بعدی قطعی است.',
      due: 'امروز',
      workId: 'work-wh-1',
      conversationId: 'thr-br-mr-184',
      createdAt: '۰۸:۱۵',
      activity: [
        { id: 'pra-1', time: '۰۸:۱۲', text: 'هشدار کمبود ماده اصطکاکی توسط عامل انبار ثبت شد.', unit: 'انبار', recordType: 'inventory', recordId: 'inv-oil-10w40' },
        { id: 'pra-2', time: '۰۸:۱۵', text: 'درخواست خرید BR-MR-184 ایجاد و برای تایید ارسال شد.', unit: 'تدارکات' },
        { id: 'pra-3', time: '۰۸:۴۰', text: 'استعلام از دو تامین‌کننده تاییدشده انجام و قیمت کاوه انتخاب شد.', unit: 'تدارکات' },
      ],
    },
    {
      id: 'BR-MR-191',
      title: 'خرید رنگ پودری اپوکسی خط پرداخت',
      status: 'pending',
      unitId: 'unit-proc',
      requester: 'سرپرست انبار',
      approver: 'مدیر مالی',
      supplier: 'پوشش‌های صنعتی البرز',
      amount: 92000000,
      amountLabel: '۹۲ میلیون تومان',
      quantity: 10,
      itemId: 'inv-powder',
      reason: 'نزدیک شدن به نقطه سفارش پیش از شروع سری تولید FG-8845.',
      due: '۲۱ مرداد',
      workId: 'work-wh-2',
      createdAt: 'دیروز',
      activity: [{ id: 'pra-4', time: 'دیروز', text: 'پیش‌نویس درخواست ثبت شد.', unit: 'انبار' }],
    },
    {
      id: 'PR-196',
      title: 'خرید قالب یدکی پرس ۲ (کد T-118)',
      status: 'pending',
      unitId: 'unit-hr',
      requester: 'سرپرست نت',
      approver: 'مدیر مالی',
      supplier: 'ابزارسازی مهرگان',
      amount: 264000000,
      amountLabel: '۲۶۴ میلیون تومان',
      quantity: 2,
      itemId: 'inv-backplate',
      reason: 'فرسودگی قالب فعلی روی ضخامت نهایی اثر گذاشته و ریسک تکرار مردودی QC را بالا برده است.',
      due: '۲۳ مرداد',
      workId: 'work-maint-1',
      createdAt: '۰۷:۳۰',
      activity: [{ id: 'pra-5', time: '۰۷:۳۰', text: 'درخواست پس از گزارش بازرسی قالب ثبت شد.', unit: 'نگهداری' }],
    },
  ],
  transactions: [
    {
      id: 'BR-MNT-442',
      title: 'هزینه نگهداری اضطراری پرس هیدرولیک ۲',
      amount: 320000000,
      amountLabel: '۳۲۰ میلیون تومان',
      unitId: 'unit-hr',
      category: 'نگهداری',
      period: 'مرداد ۱۴۰۵',
      status: 'pending',
      evidence: ['فاکتور پیمانکار هیدرولیک #۵۵۲۱', 'گزارش بازدید فنی ۱۷ مرداد', 'مقایسه با قرارداد سالانه نگهداری'],
      comparison: '۲۲٪ بالاتر از میانگین ماهانه نگهداری؛ هر شیفت توقف پرس ۲ حدود ۲٫۸ هزار جفت تولید را از دست می‌دهد.',
      approvalId: 'APR-102',
      workId: 'work-fin-1',
      agentId: 'agent-fin',
    },
    {
      id: 'BR-FRT-451',
      title: 'هزینه حمل اضطراری مواد اولیه',
      amount: 58000000,
      amountLabel: '۵۸ میلیون تومان',
      unitId: 'unit-fin',
      category: 'حمل',
      period: 'هفته جاری',
      status: 'pending',
      evidence: ['بارنامه حمل #۷۷۱', 'دو سفارش اضطراری در ۱۰ روز', 'مقایسه با نرخ حمل قرارداد'],
      comparison: 'نسبت به الگوی ماهانه ۱۹٪ بالاتر؛ ریشه آن سفارش‌های اضطراری ماده اصطکاکی است.',
      workId: 'work-fin-2',
      agentId: 'agent-fin',
    },
    {
      id: 'BR-REV-460',
      title: 'فروش محقق‌شده سری FG-8840 — تجمیع',
      amount: 3120000000,
      amountLabel: '۳٫۱۲ میلیارد تومان',
      unitId: 'unit-re',
      category: 'فروش',
      period: 'هفته جاری',
      status: 'approved',
      evidence: ['محموله SH-1201 و SH-1204', 'صورتحساب مشتریان بازار یدکی'],
      comparison: '+۶٫۲٪ نسبت به میانگین ۷ روز.',
      agentId: 'agent-re',
    },
    {
      id: 'TX-468',
      title: 'هزینه ضایعات بچ مردود BATCH-2417',
      amount: 74000000,
      amountLabel: '۷۴ میلیون تومان',
      unitId: 'unit-agri',
      category: 'ضایعات',
      period: 'مرداد ۱۴۰۵',
      status: 'pending',
      evidence: ['برگه قرنطینه QC-0241', 'وزن ضایعات ۹۸۰ کیلوگرم', 'بهای تمام‌شده مواد بچ'],
      comparison: 'سومین بچ مردود در ۳۰ روز؛ الگوی تکرارشونده روی پارامتر پخت.',
      workId: 'work-qc-1',
      agentId: 'agent-agri',
    },
  ],
  employees: [
    {
      id: 'emp-mosavi',
      name: 'علی موسوی',
      role: 'اپراتور پرس ۲',
      unitId: 'unit-fuel',
      lateTodayMinutes: 35,
      attendanceRate: 91,
      workId: 'work-hr-1',
      alertId: 'alert-hr-late',
      history: [
        { date: '۱۸ مرداد', status: 'تاخیر ۳۵ دقیقه', note: 'شیفت صبح خط پرس' },
        { date: '۱۷ مرداد', status: 'به‌موقع' },
        { date: '۱۶ مرداد', status: 'به‌موقع' },
        { date: '۱۵ مرداد', status: 'تاخیر ۱۲ دقیقه' },
      ],
    },
    {
      id: 'emp-karimi',
      name: 'مریم کریمی',
      role: 'بازرس آزمایشگاه کیفیت',
      unitId: 'unit-agri',
      attendanceRate: 99,
      workId: 'work-qc-1',
      history: [
        { date: '۱۸ مرداد', status: 'به‌موقع', note: 'آزمون اصطکاک بچ BATCH-2417' },
        { date: '۱۷ مرداد', status: 'به‌موقع' },
      ],
    },
    {
      id: 'emp-nouri',
      name: 'حسین نوری',
      role: 'انباردار مواد اولیه',
      unitId: 'unit-wh',
      attendanceRate: 97,
      history: [{ date: '۱۸ مرداد', status: 'به‌موقع', note: 'شمارش رزین و الیاف' }],
    },
    {
      id: 'emp-rasouli',
      name: 'سعید رسولی',
      role: 'تکنسین نگهداری هیدرولیک',
      unitId: 'unit-hr',
      attendanceRate: 95,
      workId: 'work-maint-1',
      history: [
        { date: '۱۸ مرداد', status: 'اضافه‌کاری', note: 'عیب‌یابی نشتی پرس ۲ از ۰۶:۴۰' },
        { date: '۱۷ مرداد', status: 'به‌موقع' },
      ],
    },
  ],
  correspondence: [
    {
      id: 'BR-CORR-412',
      number: '۴۱۲/ک',
      title: 'درخواست گزارش اقدام اصلاحی برای بچ BATCH-2417',
      from: 'قطعه‌گستر پارس — واحد تضمین کیفیت',
      to: 'کارخانه لنت ترمز آریاترمز',
      status: 'awaiting_reply',
      deadline: '۲۰ مرداد',
      owner: 'دبیرخانه فنی',
      summary: 'مشتری OEM گزارش ۸D و مستندات ترخیص بچ‌های بعدی را تا مهلت اعلام‌شده درخواست کرده است.',
      workId: 'work-corr-1',
      conversationId: 'thr-corr-412',
      demoNote: 'مسیر ارجاع و سطوح تایید دقیق مکاتبات فنی هنوز قطعی نشده؛ این گردش یک سناریوی نمایشی است.',
      history: [
        { id: 'ch-1', time: '۱۵ مرداد', text: 'نامه مشتری ثبت شد.' },
        { id: 'ch-2', time: '۱۶ مرداد', text: 'ارجاع به کنترل کیفیت و مدیریت کارخانه (نمونه دمو).' },
        { id: 'ch-3', time: '۱۷ مرداد', text: 'یادآوری مهلت پاسخ توسط عامل مکاتبات.' },
      ],
    },
  ],
  alerts: [
    {
      id: 'alert-inv-friction',
      title: 'کمبود ماده اصطکاکی رزین فنولیک',
      summary: 'موجودی ۱۴ کیسه؛ اتمام تقریبی ۲٫۳ روز. درخواست BR-MR-184 در انتظار تایید شماست.',
      unitId: 'unit-wh',
      priority: 'critical',
      type: 'موجودی',
      time: '۰۸:۱۲',
      status: 'open',
      recordType: 'inventory',
      recordId: 'inv-oil-10w40',
      workId: 'work-wh-1',
    },
    {
      id: 'alert-qc-556',
      title: 'شکست QC بچ BATCH-2417',
      summary: 'ضریب اصطکاک نمونه خارج از پنجره مجاز؛ ۹۸۰ کیلوگرم بچ قرنطینه شد — QC-0241.',
      unitId: 'unit-agri',
      priority: 'critical',
      type: 'کیفیت',
      time: '۰۷:۲۰',
      status: 'open',
      recordType: 'work',
      recordId: 'work-qc-1',
      workId: 'work-qc-1',
    },
    {
      id: 'alert-press-stop',
      title: 'توقف پرس هیدرولیک ۲',
      summary: 'نشتی سیستم هیدرولیک از ۰۶:۴۰؛ هر شیفت توقف حدود ۲٫۸ هزار جفت تولید را حذف می‌کند.',
      unitId: 'unit-hr',
      priority: 'critical',
      type: 'توقف خط',
      time: '۰۶:۴۰',
      status: 'open',
      recordType: 'work',
      recordId: 'work-maint-1',
      workId: 'work-maint-1',
    },
    {
      id: 'alert-fin-maint',
      title: 'تایید هزینه نگهداری پرس ۲',
      summary: 'تراکنش BR-MNT-442 به مبلغ ۳۲۰ میلیون در انتظار تایید مدیریت کارخانه.',
      unitId: 'unit-fin',
      priority: 'high',
      type: 'مالی',
      time: '۰۷:۴۵',
      status: 'open',
      recordType: 'transaction',
      recordId: 'BR-MNT-442',
      workId: 'work-fin-1',
    },
    {
      id: 'alert-so-3092',
      title: 'تعهد تحویل SO-3092 در خطر',
      summary: 'موجودی FG-8842 برای تکمیل سفارش کافی نیست؛ تحویل ۲۲ مرداد بدون بچ جایگزین محقق نمی‌شود.',
      unitId: 'unit-re',
      priority: 'high',
      type: 'تعهد تحویل',
      time: '۰۹:۱۰',
      status: 'open',
      recordType: 'work',
      recordId: 'work-re-1',
      workId: 'work-re-1',
    },
    {
      id: 'alert-so-backlog',
      title: 'دستور تولید PROD-1148 معوق',
      summary: 'SO-3081 نه روز در صف است؛ PROD-1148 به‌خاطر توقف پرس ۲ صادر نشده و برنامه هفته را عقب می‌اندازد.',
      unitId: 'unit-plan',
      priority: 'medium',
      type: 'سفارش فروش',
      time: 'دیروز',
      status: 'open',
      recordType: 'work',
      recordId: 'work-plan-1',
      workId: 'work-plan-1',
    },
    {
      id: 'alert-corr-412',
      title: 'درخواست اقدام اصلاحی مشتری بدون پاسخ',
      summary: 'نامه ۴۱۲/ک قطعه‌گستر پارس تا ۲۰ مرداد نیازمند گزارش ۸D است.',
      unitId: 'unit-corr',
      priority: 'high',
      type: 'مکاتبه',
      time: 'دیروز',
      status: 'open',
      recordType: 'correspondence',
      recordId: 'BR-CORR-412',
      workId: 'work-corr-1',
    },
    {
      id: 'alert-hr-late',
      title: 'تاخیر حضور اپراتور پرس ۲',
      summary: 'علی موسوی ۳۵ دقیقه تاخیر در شیفت صبح خط پرس.',
      unitId: 'unit-fuel',
      priority: 'medium',
      type: 'حضور و غیاب',
      time: '۰۶:۵۰',
      status: 'open',
      recordType: 'employee',
      recordId: 'emp-mosavi',
      workId: 'work-hr-1',
    },
  ],
  goals: [
    {
      id: 'goal-1',
      title: 'رساندن تولید ماهانه به ۳۲۰ هزار جفت لنت',
      owner: 'عامل تولید و پرس',
      progress: 68,
      target: '۳۲۰ هزار جفت',
      due: '۳۱ مرداد ۱۴۰۵',
      status: 'در مسیر',
      unitId: 'unit-fuel',
      initiativeIds: ['init-1'],
      workIds: ['work-fuel-1', 'work-plan-1'],
    },
    {
      id: 'goal-2',
      title: 'کاهش نرخ توقف خط پرس به زیر ۴٪',
      owner: 'عامل نگهداری',
      progress: 41,
      target: 'حداکثر ۴٪ زمان توقف',
      due: '۲۸ مرداد ۱۴۰۵',
      status: 'نیازمند اقدام',
      unitId: 'unit-hr',
      initiativeIds: ['init-2'],
      workIds: ['work-maint-1', 'work-fin-1'],
      risk: 'BR-MNT-442 هنوز تایید نشده و پرس ۲ متوقف است',
    },
    {
      id: 'goal-3',
      title: 'کاهش نرخ مردودی بچ به زیر ۲٪',
      owner: 'عامل کنترل کیفیت',
      progress: 52,
      target: 'کمتر از ۲٪ مردودی',
      due: '۱۰ شهریور ۱۴۰۵',
      status: 'نیازمند اقدام',
      unitId: 'unit-agri',
      initiativeIds: ['init-3'],
      workIds: ['work-qc-1', 'work-corr-1'],
      risk: 'سومین بچ مردود در ۳۰ روز',
    },
    {
      id: 'goal-4',
      title: 'تحویل به‌موقع سفارش‌ها بالای ۹۵٪',
      owner: 'عامل فروش',
      progress: 74,
      target: '۹۵٪ OTD',
      due: '۳۱ مرداد ۱۴۰۵',
      status: 'در مسیر',
      unitId: 'unit-re',
      initiativeIds: ['init-4'],
      workIds: ['work-re-1', 'work-ship-1'],
      risk: 'SO-3092 در معرض تاخیر',
    },
    {
      id: 'goal-5',
      title: 'پایداری تامین مواد اصلی و حذف خرید اضطراری',
      owner: 'عامل تدارکات',
      progress: 46,
      target: 'حداکثر ۲ قلم زیر نقطه سفارش',
      due: '۲۵ مرداد ۱۴۰۵',
      status: 'نیازمند اقدام',
      unitId: 'unit-proc',
      initiativeIds: ['init-5'],
      workIds: ['work-wh-1', 'work-proc-1'],
      risk: 'BR-MR-184 در انتظار تایید',
    },
  ],
  initiatives: [
    { id: 'init-1', title: 'تعادل توالی بچ و ظرفیت کوره پخت', goalId: 'goal-1', status: 'فعال', workIds: ['work-fuel-1', 'work-plan-1'] },
    { id: 'init-2', title: 'برنامه نگهداری پیشگیرانه پرس‌ها', goalId: 'goal-2', status: 'فعال', workIds: ['work-maint-1'] },
    { id: 'init-3', title: 'تثبیت پارامتر پخت و بازنگری فرمول', goalId: 'goal-3', status: 'فعال', workIds: ['work-qc-1'] },
    { id: 'init-4', title: 'هماهنگی تخصیص محصول نهایی با تعهد تحویل', goalId: 'goal-4', status: 'فعال', workIds: ['work-re-1', 'work-ship-1'] },
    { id: 'init-5', title: 'بازبینی نقطه سفارش مواد اصطکاکی', goalId: 'goal-5', status: 'فعال', workIds: ['work-wh-1', 'work-proc-1'] },
  ],
  workItems: [
    {
      id: 'work-wh-1',
      title: 'تامین اضطراری ماده اصطکاکی رزین فنولیک',
      type: 'خرید',
      stage: 'مشاهده',
      owner: 'عامل تدارکات',
      unitId: 'unit-proc',
      priority: 'critical',
      updated: '۰۸:۱۵',
      description: 'درخواست BR-MR-184 برای جلوگیری از توقف اختلاط و پرس بچ‌های B-2419 به بعد.',
      linked: ['inv-oil-10w40', 'BR-MR-184', 'alert-inv-friction', 'thr-br-mr-184'],
      recordType: 'purchase',
      recordId: 'BR-MR-184',
      goalId: 'goal-5',
      conversationId: 'thr-br-mr-184',
    },
    {
      id: 'work-wh-2',
      title: 'تکمیل موجودی رنگ پودری خط پرداخت',
      type: 'خرید',
      stage: 'آماده‌سازی',
      owner: 'عامل انبار',
      unitId: 'unit-wh',
      priority: 'medium',
      updated: 'دیروز',
      description: 'BR-MR-191 پیش از شروع سری FG-8845.',
      linked: ['BR-MR-191', 'inv-powder'],
      recordType: 'purchase',
      recordId: 'BR-MR-191',
      goalId: 'goal-5',
    },
    {
      id: 'work-maint-1',
      title: 'رفع نشتی هیدرولیک و راه‌اندازی پرس ۲',
      type: 'نگهداری',
      stage: 'در حال اجرا',
      owner: 'عامل نگهداری',
      unitId: 'unit-hr',
      priority: 'critical',
      updated: '۰۸:۵۰',
      description: 'توقف از ۰۶:۴۰؛ تعویض شیر و آب‌بندی جک اصلی، وابسته به تایید BR-MNT-442.',
      linked: ['BR-MNT-442', 'PR-196', 'alert-press-stop', 'thr-br-mnt-442'],
      recordType: 'transaction',
      recordId: 'BR-MNT-442',
      goalId: 'goal-2',
      conversationId: 'thr-br-mnt-442',
    },
    {
      id: 'work-qc-1',
      title: 'اقدام اصلاحی بچ مردود BATCH-2417',
      type: 'کیفیت',
      stage: 'در حال اجرا',
      owner: 'عامل کنترل کیفیت',
      unitId: 'unit-agri',
      priority: 'critical',
      updated: '۰۷:۳۵',
      description: 'برگه QC-0241: قرنطینه ۹۸۰ کیلوگرم، بازآزمون نمونه و بررسی پروفیل دمای کوره پخت.',
      linked: ['TX-468', 'alert-qc-556', 'BR-CORR-412', 'thr-qc-556'],
      recordType: 'transaction',
      recordId: 'TX-468',
      goalId: 'goal-3',
      conversationId: 'thr-qc-556',
    },
    {
      id: 'work-fin-1',
      title: 'تایید هزینه نگهداری اضطراری پرس ۲',
      type: 'مالی',
      stage: 'مشاهده',
      owner: 'عامل مالی',
      unitId: 'unit-fin',
      priority: 'high',
      updated: '۰۷:۵۰',
      description: 'تراکنش BR-MNT-442 / APR-102 در انتظار تایید مدیر کارخانه.',
      linked: ['BR-MNT-442', 'alert-fin-maint', 'thr-br-mnt-442'],
      recordType: 'transaction',
      recordId: 'BR-MNT-442',
      goalId: 'goal-2',
      conversationId: 'thr-br-mnt-442',
    },
    {
      id: 'work-fin-2',
      title: 'بازبینی هزینه حمل اضطراری مواد',
      type: 'مالی',
      stage: 'در حال اجرا',
      owner: 'عامل مالی',
      unitId: 'unit-fin',
      priority: 'high',
      updated: '۰۸:۳۵',
      description: 'ناهنجاری ۱۹٪ در هزینه حمل — BR-FRT-451.',
      linked: ['BR-FRT-451', 'inv-oil-10w40'],
      recordType: 'transaction',
      recordId: 'BR-FRT-451',
      goalId: 'goal-5',
    },
    {
      id: 'work-re-1',
      title: 'تعیین تکلیف تعهد تحویل SO-3092',
      type: 'فروش',
      stage: 'مشاهده',
      owner: 'عامل فروش',
      unitId: 'unit-re',
      priority: 'high',
      updated: '۰۹:۱۰',
      description: 'کسری ۶۴۰ جفت FG-8842 برای سفارش قطعه‌گستر پارس؛ گزینه‌ها: تخصیص از بچ BATCH-2418 یا تحویل مرحله‌ای.',
      linked: ['inv-fg-8842', 'alert-so-3092', 'thr-so-3092', 'SH-1207'],
      recordType: 'inventory',
      recordId: 'inv-fg-8842',
      goalId: 'goal-4',
      conversationId: 'thr-so-3092',
    },
    {
      id: 'work-plan-1',
      title: 'صدور دستور تولید برای سفارش معوق SO-3081',
      type: 'برنامه‌ریزی',
      stage: 'آماده‌سازی',
      owner: 'عامل برنامه‌ریزی',
      unitId: 'unit-plan',
      priority: 'medium',
      updated: '۰۸:۰۵',
      description: 'PROD-1148 پس از آزادسازی ظرفیت پرس ۲ قابل صدور است.',
      linked: ['alert-so-backlog', 'work-maint-1'],
      recordType: 'unit',
      recordId: 'unit-plan',
      goalId: 'goal-1',
    },
    {
      id: 'work-fuel-1',
      title: 'تثبیت نرخ تولید خط پرس ۱',
      type: 'تولید',
      stage: 'مجاز',
      owner: 'سرپرست خط پرس',
      unitId: 'unit-fuel',
      priority: 'medium',
      updated: '۰۹:۰۰',
      description: 'جبران بخشی از توقف پرس ۲ با شیفت فشرده روی پرس ۱.',
      linked: ['goal-1', 'work-maint-1'],
      recordType: 'unit',
      recordId: 'unit-fuel',
      goalId: 'goal-1',
    },
    {
      id: 'work-ship-1',
      title: 'آماده‌سازی محموله SH-1207',
      type: 'ارسال',
      stage: 'در حال اجرا',
      owner: 'عامل فروش',
      unitId: 'unit-re',
      priority: 'medium',
      updated: '۰۸:۴۵',
      description: 'بارگیری ۷۲۰ جفت FG-8842 و صدور اسناد ارسال برای مشتری بازار یدکی.',
      linked: ['inv-fg-8842', 'BR-REV-460'],
      recordType: 'inventory',
      recordId: 'inv-fg-8842',
      goalId: 'goal-4',
    },
    {
      id: 'work-proc-1',
      title: 'بازبینی نقطه سفارش الیاف و رزین',
      type: 'تامین',
      stage: 'پیشنهاد',
      owner: 'عامل تدارکات',
      unitId: 'unit-proc',
      priority: 'medium',
      updated: '۰۷:۴۰',
      description: 'تنظیم نقطه سفارش بر اساس مصرف واقعی ۳۰ روز و زمان تحویل تامین‌کننده.',
      linked: ['inv-fiber', 'inv-oil-10w40'],
      recordType: 'inventory',
      recordId: 'inv-fiber',
      goalId: 'goal-5',
    },
    {
      id: 'work-corr-1',
      title: 'پاسخ به نامه اقدام اصلاحی ۴۱۲/ک',
      type: 'مکاتبه',
      stage: 'در حال اجرا',
      owner: 'عامل مکاتبات',
      unitId: 'unit-corr',
      priority: 'high',
      updated: 'دیروز',
      description: 'تهیه گزارش ۸D و پیوست نتایج بازآزمون بچ BATCH-2417.',
      linked: ['BR-CORR-412', 'work-qc-1', 'thr-corr-412'],
      recordType: 'correspondence',
      recordId: 'BR-CORR-412',
      goalId: 'goal-3',
      conversationId: 'thr-corr-412',
    },
    {
      id: 'work-hr-1',
      title: 'پیگیری تاخیر اپراتور پرس ۲',
      type: 'نیروی انسانی',
      stage: 'پیشنهاد',
      owner: 'سرپرست خط پرس',
      unitId: 'unit-fuel',
      priority: 'medium',
      updated: '۰۷:۱۰',
      description: 'ثبت تاخیر ۳۵ دقیقه‌ای و نیاز به گفتگوی سرپرست شیفت.',
      linked: ['emp-mosavi', 'alert-hr-late'],
      recordType: 'employee',
      recordId: 'emp-mosavi',
    },
  ],
  threads: [
    {
      id: 'thr-br-mr-184',
      title: 'تایید خرید BR-MR-184 — ماده اصطکاکی',
      channel: 'تدارکات',
      participants: ['کارشناس تدارکات', 'سرپرست انبار', 'مدیر مالی', 'مهندس آریا'],
      unread: 2,
      updated: '۰۸:۴۰',
      preview: 'درخواست خرید BR-MR-184 برای تایید ارسال شد.',
      relatedWork: 'work-wh-1',
      relatedRecordType: 'purchase',
      relatedRecordId: 'BR-MR-184',
      messages: [
        {
          id: 'm1',
          from: 'عامل انبار',
          body: 'موجودی رزین فنولیک SP-1068 به ۱۴ کیسه رسیده. با مصرف ۶ کیسه در روز، اتمام تقریبی ۲٫۳ روز.',
          time: '۰۸:۱۲',
          imageSrc: '/media/brake-press-line.png',
          imageCaption: 'نمای خط پرس مرتبط با توقف تولید',
          linkType: 'inventory',
          linkId: 'inv-oil-10w40',
          linkLabel: 'مشاهده موجودی',
        },
        {
          id: 'm2',
          from: 'عامل تدارکات',
          body: 'درخواست خرید BR-MR-184 برای ۶۰ کیسه از شیمی پلیمر کاوه ثبت شد.',
          time: '۰۸:۱۵',
          linkType: 'purchase',
          linkId: 'BR-MR-184',
          linkLabel: 'باز کردن BR-MR-184',
        },
        {
          id: 'm3',
          from: 'عامل مالی',
          body: 'مبلغ در سقف تایید مدیر کارخانه است. اگر امروز تایید نشود، اختلاط بچ B-2419 متوقف می‌شود.',
          time: '۰۸:۴۰',
        },
      ],
    },
    {
      id: 'thr-br-mnt-442',
      title: 'نگهداری اضطراری پرس ۲ و تایید BR-MNT-442',
      channel: 'نگهداری',
      participants: ['عامل نگهداری', 'عامل مالی', 'سرپرست خط پرس', 'مهندس آریا'],
      unread: 1,
      updated: '۰۸:۵۵',
      preview: 'BR-MNT-442 آماده تایید است.',
      relatedWork: 'work-fin-1',
      relatedRecordType: 'transaction',
      relatedRecordId: 'BR-MNT-442',
      messages: [
        {
          id: 'mf1',
          from: 'عامل مالی',
          body: 'هزینه نگهداری اضطراری پرس ۲ با کد BR-MNT-442 به مبلغ ۳۲۰ میلیون آماده تایید است.',
          time: '۰۷:۵۰',
          linkType: 'transaction',
          linkId: 'BR-MNT-442',
          linkLabel: 'مشاهده تراکنش',
        },
        {
          id: 'mf2',
          from: 'عامل نگهداری',
          body: 'شیر هیدرولیک و آب‌بندی جک اصلی باید تعویض شود؛ بدون تایید امروز، توقف تا شیفت شب ادامه می‌یابد.',
          time: '۰۸:۲۰',
          linkType: 'work',
          linkId: 'work-maint-1',
          linkLabel: 'کار نگهداری',
        },
        {
          id: 'mf3',
          from: 'سرپرست خط پرس',
          body: 'هر شیفت توقف پرس ۲ حدود ۲٫۸ هزار جفت از برنامه امروز کم می‌کند.',
          time: '۰۸:۵۵',
        },
      ],
    },
    {
      id: 'thr-qc-556',
      title: 'مردودی QC-0241 بچ BATCH-2417',
      channel: 'کیفیت',
      participants: ['عامل کنترل کیفیت', 'سرپرست خط پرس', 'عامل برنامه‌ریزی'],
      unread: 1,
      updated: '۰۷:۳۵',
      preview: 'بچ BATCH-2417 قرنطینه شد.',
      relatedWork: 'work-qc-1',
      relatedRecordType: 'work',
      relatedRecordId: 'work-qc-1',
      messages: [
        {
          id: 'mq1',
          from: 'عامل کنترل کیفیت',
          body: 'ضریب اصطکاک نمونه بچ BATCH-2417 خارج از پنجره مجاز بود؛ ۹۸۰ کیلوگرم قرنطینه شد.',
          time: '۰۷:۲۰',
          linkType: 'work',
          linkId: 'work-qc-1',
          linkLabel: 'پرونده اقدام اصلاحی',
        },
        {
          id: 'mq2',
          from: 'عامل برنامه‌ریزی',
          body: 'با حذف این بچ، تحویل SO-3092 هم تحت فشار قرار می‌گیرد.',
          time: '۰۷:۳۵',
          linkType: 'work',
          linkId: 'work-re-1',
          linkLabel: 'تعهد تحویل',
        },
      ],
    },
    {
      id: 'thr-so-3092',
      title: 'تعهد تحویل SO-3092 قطعه‌گستر پارس',
      channel: 'فروش',
      participants: ['عامل فروش', 'عامل برنامه‌ریزی', 'سرپرست انبار'],
      unread: 1,
      updated: '۰۹:۱۰',
      preview: 'کسری ۶۴۰ جفت برای تکمیل سفارش.',
      relatedWork: 'work-re-1',
      relatedRecordType: 'inventory',
      relatedRecordId: 'inv-fg-8842',
      messages: [
        {
          id: 'ms1',
          from: 'عامل فروش',
          body: 'برای SO-3092 حدود ۶۴۰ جفت FG-8842 کسری داریم و مهلت تحویل ۲۲ مرداد است.',
          time: '۰۹:۰۰',
          linkType: 'inventory',
          linkId: 'inv-fg-8842',
          linkLabel: 'موجودی محصول',
        },
        {
          id: 'ms2',
          from: 'عامل برنامه‌ریزی',
          body: 'اگر پرس ۲ تا امشب راه بیفتد، بچ BATCH-2418 روز ۲۰ آماده ترخیص QC می‌شود.',
          time: '۰۹:۱۰',
        },
      ],
    },
    {
      id: 'thr-corr-412',
      title: 'نامه مشتری ۴۱۲/ک — گزارش ۸D',
      channel: 'مکاتبات',
      participants: ['عامل مکاتبات', 'عامل کنترل کیفیت', 'مدیریت کارخانه'],
      unread: 1,
      updated: 'دیروز',
      preview: 'مهلت پاسخ ۲۰ مرداد است.',
      relatedWork: 'work-corr-1',
      relatedRecordType: 'correspondence',
      relatedRecordId: 'BR-CORR-412',
      messages: [
        {
          id: 'mc1',
          from: 'عامل مکاتبات',
          body: 'نامه ۴۱۲/ک ثبت و به کنترل کیفیت ارجاع شد. این مسیر ارجاع نمونه دمو است.',
          time: '۱۶ مرداد',
          linkType: 'correspondence',
          linkId: 'BR-CORR-412',
          linkLabel: 'مشاهده نامه',
        },
      ],
    },
    {
      id: 'thr-hr-late',
      title: 'تاخیر شیفت صبح خط پرس',
      channel: 'تولید',
      participants: ['سرپرست خط پرس', 'عامل تولید و پرس'],
      unread: 0,
      updated: '۰۷:۱۵',
      preview: 'پیشنهاد ایجاد کار پیگیری.',
      relatedWork: 'work-hr-1',
      relatedRecordType: 'employee',
      relatedRecordId: 'emp-mosavi',
      messages: [
        {
          id: 'mh1',
          from: 'عامل تولید و پرس',
          body: 'علی موسوی امروز ۳۵ دقیقه تاخیر داشته و راه‌اندازی پرس ۱ عقب افتاد.',
          time: '۰۷:۰۰',
          linkType: 'employee',
          linkId: 'emp-mosavi',
          linkLabel: 'پرونده حضور',
        },
      ],
    },
  ],
  agents: [
    {
      id: 'agent-exec',
      name: 'عامل نظارت اجرایی',
      role: 'مرکز فرماندهی',
      domain: 'مدیریت کارخانه',
      unitId: 'unit-holding',
      status: 'active',
      mastery: 88,
      alignment: 91,
      summary: 'پایش یکپارچه خط تولید، کیفیت و تامین؛ اولویت‌بندی تصمیم‌های امروز مدیر کارخانه.',
      kpis: [
        { id: 'k1', label: 'موارد نیازمند تصمیم', value: '۸', delta: 2, hint: 'امروز' },
        { id: 'k2', label: 'پیشرفت اهداف ماهانه', value: '۵۶٪', delta: 1, hint: '۵ هدف فعال' },
        { id: 'k3', label: 'واحدهای در هشدار', value: '۵', delta: 2, hint: 'تولید، کیفیت، نگهداری، انبار، فروش' },
        { id: 'k4', label: 'تازگی داده', value: now, delta: 0, hint: 'آخرین همگام‌سازی' },
      ],
      workIds: ['work-wh-1', 'work-fin-1', 'work-qc-1'],
      riskIds: ['alert-inv-friction', 'alert-qc-556', 'alert-press-stop'],
      decisionIds: ['BR-MR-184', 'BR-MNT-442'],
      systems: ['داشبورد اجرایی', 'کارتابل تایید'],
      activity: [
        { id: 'ae1', time: '۰۹:۳۰', text: 'خلاصه اجرایی برای مدیر کارخانه آماده شد.' },
        { id: 'ae2', time: '۰۸:۴۰', text: '۸ مورد نیازمند تصمیم اولویت‌بندی شد.' },
      ],
    },
    {
      id: 'agent-fin',
      name: 'مالی و تسویه عاملین',
      role: 'مالی و تسویه عاملین',
      domain: 'مالی و تسویه',
      unitId: 'unit-fin',
      status: 'attention',
      mastery: 84,
      alignment: 87,
      summary: 'نقدینگی پایدار است اما هزینه نگهداری، خرید اضطراری و ضایعات بچ در صف تایید قرار دارند.',
      kpis: [
        { id: 'fk1', label: 'نقد عملیاتی', value: '۸٫۴ میلیارد', delta: -2.6, hint: 'پس از صف پرداخت' },
        { id: 'fk2', label: 'فروش هفته', value: '۳٫۱۲ میلیارد', delta: 6.2, hint: 'نسبت به میانگین ۷ روز' },
        { id: 'fk3', label: 'تایید باز', value: '۳', delta: 1, hint: 'BR-MNT-442 · BR-FRT-451 · TX-468' },
        { id: 'fk4', label: 'هزینه توقف خط', value: '۲۱۰ میلیون', delta: 18, hint: 'تخمین امروز' },
      ],
      workIds: ['work-fin-1', 'work-fin-2'],
      riskIds: ['alert-fin-maint'],
      decisionIds: ['BR-MNT-442', 'BR-FRT-451', 'TX-468'],
      systems: ['دفتر مالی', 'کارتابل تایید'],
      activity: [
        { id: 'af1', time: '۰۸:۵۵', text: 'یادآوری تایید BR-MNT-442 به مدیر کارخانه.' },
        { id: 'af2', time: '۰۸:۳۰', text: 'ناهنجاری هزینه حمل BR-FRT-451 ثبت شد.' },
      ],
      dashboardKind: 'finance-settlement',
      pinDefault: true,
    },
    {
      id: 'agent-wh',
      name: 'عامل انبار',
      role: 'موجودی مواد و محصول',
      domain: 'انبارداری',
      unitId: 'unit-wh',
      status: 'attention',
      mastery: 82,
      alignment: 85,
      summary: 'ماده اصطکاکی زیر نقطه سفارش است؛ موجودی محصول نهایی هم برای SO-3092 کفایت نمی‌کند.',
      kpis: [
        { id: 'wk1', label: 'زیر نقطه سفارش', value: '۵', delta: 12, hint: 'قلم' },
        { id: 'wk2', label: 'روز تا اتمام ماده اصطکاکی', value: '۲٫۳', delta: -38, hint: 'بر اساس مصرف ۷ روز' },
        { id: 'wk3', label: 'درخواست باز', value: '۳', delta: 1, hint: 'BR-MR-184 / BR-MR-191 / PR-196' },
        { id: 'wk4', label: 'موجودی FG-8842', value: '۱۸۶۰ جفت', delta: -14, hint: 'کسری برای SO-3092' },
      ],
      workIds: ['work-wh-1', 'work-wh-2'],
      riskIds: ['alert-inv-friction', 'alert-so-3092'],
      decisionIds: ['BR-MR-184'],
      systems: ['انبار دیجیتال', 'خرید'],
      activity: [{ id: 'aw1', time: '۰۸:۱۵', text: 'BR-MR-184 ایجاد شد.' }],
    },
    {
      id: 'agent-fuel',
      name: 'تولید',
      role: 'عملیات تولید',
      domain: 'تولید',
      unitId: 'unit-fuel',
      status: 'attention',
      mastery: 87,
      alignment: 86,
      summary: 'خط پرس ۱ پایدار است اما توقف پرس ۲ برنامه امروز را زیر فشار گذاشته.',
      kpis: [
        { id: 'ok1', label: 'تولید دیروز', value: '۱۱٫۶ هزار جفت', delta: 6.2, hint: 'vs میانگین ۷ روز' },
        { id: 'ok2', label: 'راندمان خط (OEE)', value: '۷۴٪', delta: -5, hint: 'اثر توقف پرس ۲' },
        { id: 'ok3', label: 'بچ در جریان', value: 'BATCH-2418', delta: 0, hint: 'مرحله پخت' },
        { id: 'ok4', label: 'زمان توقف امروز', value: '۳ ساعت', delta: 30, hint: 'پرس ۲' },
      ],
      workIds: ['work-fuel-1', 'work-hr-1'],
      riskIds: ['alert-press-stop', 'alert-hr-late'],
      decisionIds: [],
      systems: ['سامانه پایش خط', 'ثبت بچ'],
      activity: [{ id: 'ao1', time: '۰۹:۰۵', text: 'بچ BATCH-2418 وارد کوره پخت شد.' }],
      dashboardKind: 'production',
      pinDefault: true,
    },
    {
      id: 'agent-plan',
      name: 'عامل برنامه‌ریزی تولید',
      role: 'برنامه‌ریزی و توالی بچ',
      domain: 'برنامه‌ریزی',
      unitId: 'unit-plan',
      status: 'attention',
      mastery: 81,
      alignment: 88,
      summary: 'شش دستور تولید باز است و یک سفارش معوق منتظر آزادسازی ظرفیت پرس مانده.',
      kpis: [
        { id: 'pk1', label: 'دستور تولید باز', value: '۶', delta: 1, hint: 'PROD-1141 تا PROD-1148' },
        { id: 'pk2', label: 'سفارش بدون دستور', value: '۱', delta: 1, hint: 'SO-3081' },
        { id: 'pk3', label: 'بار ظرفیت پرس', value: '۸۹٪', delta: 7, hint: 'هفته جاری' },
        { id: 'pk4', label: 'انحراف برنامه', value: '−۲٫۴ هزار جفت', delta: -9, hint: 'امروز' },
      ],
      workIds: ['work-plan-1', 'work-fuel-1'],
      riskIds: ['alert-so-backlog'],
      decisionIds: [],
      systems: ['برنامه‌ریزی تولید', 'ثبت بچ'],
      activity: [{ id: 'ap1', time: '۰۸:۰۵', text: 'توالی بچ‌های هفته بازچینش شد.' }],
    },
    {
      id: 'agent-agri',
      name: 'عامل کنترل کیفیت',
      role: 'آزمون و ترخیص بچ',
      domain: 'کیفیت',
      unitId: 'unit-agri',
      status: 'attention',
      mastery: 85,
      alignment: 90,
      summary: 'مردودی بچ BATCH-2417 سومین مورد در ۳۰ روز است و الگوی پارامتر پخت را نشان می‌دهد.',
      kpis: [
        { id: 'qk1', label: 'نرخ مردودی بچ', value: '۳٫۱٪', delta: 0.8, hint: '۳۰ روز' },
        { id: 'qk2', label: 'بچ قرنطینه', value: '۱', delta: 1, hint: 'BATCH-2417' },
        { id: 'qk3', label: 'ترخیص امروز', value: '۲', delta: 0, hint: 'BATCH-2415 / BATCH-2416' },
        { id: 'qk4', label: 'اقدام اصلاحی باز', value: '۱', delta: 0, hint: 'QC-0241' },
      ],
      workIds: ['work-qc-1', 'work-corr-1'],
      riskIds: ['alert-qc-556'],
      decisionIds: ['TX-468'],
      systems: ['آزمایشگاه کیفیت', 'ثبت بچ'],
      activity: [{ id: 'aq1', time: '۰۷:۲۰', text: 'برگه قرنطینه QC-0241 صادر شد.' }],
    },
    {
      id: 'agent-proc',
      name: 'تأمین',
      role: 'تأمین مواد و وابستگی تولید',
      domain: 'تأمین',
      unitId: 'unit-proc',
      status: 'attention',
      mastery: 80,
      alignment: 83,
      summary: 'دو خرید اضطراری در ده روز اخیر نشان می‌دهد نقطه سفارش مواد اصلی نیازمند بازنگری است.',
      kpis: [
        { id: 'ck1', label: 'درخواست باز', value: '۳', delta: 1, hint: 'BR-MR-184 / BR-MR-191 / PR-196' },
        { id: 'ck2', label: 'خرید اضطراری ۱۰ روز', value: '۲', delta: 100, hint: 'ماده اصطکاکی' },
        { id: 'ck3', label: 'زمان تحویل تامین‌کننده', value: '۴ روز', delta: 0, hint: 'شیمی پلیمر کاوه' },
        { id: 'ck4', label: 'انطباق قیمت', value: '−۳٪', delta: -3, hint: 'نسبت به استعلام قبلی' },
      ],
      workIds: ['work-wh-1', 'work-proc-1'],
      riskIds: ['alert-inv-friction'],
      decisionIds: ['BR-MR-184', 'BR-MR-191'],
      systems: ['خرید', 'ارزیابی تامین‌کننده'],
      activity: [{ id: 'ac2', time: '۰۸:۴۰', text: 'استعلام دو تامین‌کننده مقایسه شد.' }],
      dashboardKind: 'supply',
      pinDefault: true,
    },
    {
      id: 'agent-hr',
      name: 'عامل نگهداری',
      role: 'نگهداری و تعمیرات',
      domain: 'نگهداری',
      unitId: 'unit-hr',
      status: 'attention',
      mastery: 79,
      alignment: 84,
      summary: 'پرس ۲ متوقف است و تعمیر آن به تایید هزینه BR-MNT-442 گره خورده.',
      kpis: [
        { id: 'hk1', label: 'توقف باز', value: '۱', delta: 1, hint: 'پرس ۲' },
        { id: 'hk2', label: 'MTTR', value: '۴٫۲ ساعت', delta: 12, hint: 'میانگین ۳۰ روز' },
        { id: 'hk3', label: 'نگهداری پیشگیرانه انجام‌شده', value: '۷۸٪', delta: -6, hint: 'برنامه ماه' },
        { id: 'hk4', label: 'کار باز', value: '۲', delta: 0, hint: 'work-maint-1 / PR-196' },
      ],
      workIds: ['work-maint-1'],
      riskIds: ['alert-press-stop'],
      decisionIds: ['BR-MNT-442', 'PR-196'],
      systems: ['نگهداری و تعمیرات'],
      activity: [{ id: 'ah1', time: '۰۶:۴۵', text: 'توقف پرس ۲ ثبت و تیم هیدرولیک اعزام شد.' }],
    },
    {
      id: 'agent-re',
      name: 'عامل فروش',
      role: 'سفارش و تعهد تحویل',
      domain: 'فروش',
      unitId: 'unit-re',
      status: 'attention',
      mastery: 83,
      alignment: 85,
      summary: 'چهارده سفارش باز است و SO-3092 بدون بچ جایگزین به تعهد تحویل نمی‌رسد.',
      kpis: [
        { id: 'rk1', label: 'سفارش باز', value: '۱۴', delta: 2, hint: 'OEM و بازار یدکی' },
        { id: 'rk2', label: 'تحویل به‌موقع', value: '۹۱٪', delta: -3, hint: '۳۰ روز' },
        { id: 'rk3', label: 'سفارش در ریسک', value: '۱', delta: 1, hint: 'SO-3092' },
        { id: 'rk4', label: 'محموله امروز', value: 'SH-1207', delta: 0, hint: 'در حال بارگیری' },
      ],
      workIds: ['work-re-1', 'work-ship-1'],
      riskIds: ['alert-so-3092'],
      decisionIds: [],
      systems: ['سفارش فروش', 'ارسال و توزیع'],
      activity: [{ id: 'ar1', time: '۰۸:۴۵', text: 'بارگیری محموله SH-1207 آغاز شد.' }],
    },
    {
      id: 'agent-corr',
      name: 'عامل مکاتبات',
      role: 'مکاتبات و اسناد فنی',
      domain: 'مکاتبات',
      unitId: 'unit-corr',
      status: 'attention',
      mastery: 77,
      alignment: 82,
      summary: 'نامه اقدام اصلاحی مشتری OEM در وضعیت انتظار پاسخ است.',
      kpis: [
        { id: 'mk1', label: 'نامه معوق', value: '۱', delta: 0, hint: '۴۱۲/ک' },
        { id: 'mk2', label: 'مهلت نزدیک', value: '۲۰ مرداد', delta: 0, hint: '۲ روز' },
        { id: 'mk3', label: 'گزارش ۸D باز', value: '۱', delta: 0, hint: 'بچ BATCH-2417' },
        { id: 'mk4', label: 'سند بایگانی امروز', value: '۴', delta: 1, hint: 'گواهی آزمون' },
      ],
      workIds: ['work-corr-1'],
      riskIds: ['alert-corr-412'],
      decisionIds: ['BR-CORR-412'],
      systems: ['بایگانی دیجیتال'],
      activity: [{ id: 'am1', time: 'دیروز', text: 'یادآوری مهلت نامه ۴۱۲/ک.' }],
    },
  ],
  mapNodes: [
    { id: 'holding', label: 'کارخانه لنت ترمز آریاترمز', type: 'holding', meta: 'مرکز فرماندهی', status: 'info', unitId: 'unit-holding', agentId: 'agent-exec' },
    { id: 'plan', label: 'برنامه‌ریزی تولید', type: 'unit', parent: 'holding', status: 'warning', meta: '۶ دستور تولید باز', unitId: 'unit-plan', agentId: 'agent-plan' },
    { id: 'fuel', label: 'تولید و پرس', type: 'unit', parent: 'holding', status: 'warning', meta: 'تولید ۱۱٫۶ هزار جفت', unitId: 'unit-fuel', agentId: 'agent-fuel' },
    { id: 'agri', label: 'کنترل کیفیت', type: 'unit', parent: 'holding', status: 'danger', meta: 'بچ BATCH-2417 قرنطینه', unitId: 'unit-agri', agentId: 'agent-agri' },
    { id: 'wh', label: 'انبار مواد و محصول', type: 'unit', parent: 'holding', status: 'danger', meta: '۵ قلم زیر سفارش', unitId: 'unit-wh', agentId: 'agent-wh' },
    { id: 're', label: 'فروش و سفارش‌ها', type: 'unit', parent: 'holding', status: 'warning', meta: '۱۴ سفارش باز', unitId: 'unit-re', agentId: 'agent-re' },
    { id: 'proc', label: 'تدارکات مواد', type: 'function', parent: 'holding', status: 'danger', meta: '۳ درخواست خرید', unitId: 'unit-proc', agentId: 'agent-proc' },
    { id: 'maint', label: 'نگهداری و تعمیرات', type: 'function', parent: 'holding', status: 'danger', meta: 'توقف پرس ۲', unitId: 'unit-hr', agentId: 'agent-hr' },
    { id: 'fin', label: 'مالی', type: 'function', parent: 'holding', status: 'warning', meta: '۳ تایید باز', unitId: 'unit-fin', agentId: 'agent-fin' },
    { id: 'corr', label: 'مکاتبات و اسناد فنی', type: 'function', parent: 'holding', status: 'warning', meta: '۱ نامه معوق', unitId: 'unit-corr', agentId: 'agent-corr' },
    { id: 'agent-wh-n', label: 'عامل انبار', type: 'agent', parent: 'wh', status: 'danger', agentId: 'agent-wh' },
    { id: 'agent-qc-n', label: 'عامل کنترل کیفیت', type: 'agent', parent: 'agri', status: 'danger', agentId: 'agent-agri' },
    { id: 'agent-fin-n', label: 'عامل مالی', type: 'agent', parent: 'fin', status: 'warning', agentId: 'agent-fin' },
    { id: 'sys-mes', label: 'سامانه پایش خط و ثبت بچ', type: 'system', parent: 'fuel', status: 'info', meta: 'BATCH-* / PROD-*' },
    { id: 'sys-qms', label: 'آزمایشگاه و سوابق QC', type: 'system', parent: 'agri', status: 'info', meta: 'QC-*' },
  ],
  insights: [
    {
      id: 'ins-1',
      title: 'ریشه مردودی بچ‌ها در پروفیل دمای کوره پخت است',
      category: 'کیفیت',
      severity: 'danger',
      summary: 'هر سه بچ مردود ۳۰ روز اخیر در بازه‌ای پخت شده‌اند که دمای ناحیه دوم کوره ۱۲ درجه پایین‌تر از نقطه تنظیم بوده است.',
      evidence: ['برگه‌های QC-541، QC-549 و QC-0241', 'لاگ دمای کوره پخت ۳۰ روز', 'ثبات ضریب اصطکاک در بچ‌های ناحیه سالم'],
      recommendation: 'کالیبراسیون ترموکوپل ناحیه دوم و توقف ترخیص بچ‌های پخت‌شده در آن بازه تا بازآزمون.',
      period: '۳۰ روز اخیر',
      impact: 'حذف حدود ۷۴ میلیون تومان ضایعات در ماه',
      confidence: 'بالا',
      recordType: 'work',
      recordId: 'work-qc-1',
      workId: 'work-qc-1',
    },
    {
      id: 'ins-2',
      title: 'توقف پرس ۲ گلوگاه تعهد تحویل این هفته است',
      category: 'عملیات',
      severity: 'warning',
      summary: 'با ادامه توقف تا شیفت شب، کسری تولید به ۵٫۶ هزار جفت می‌رسد و SO-3092 قابل تحویل نیست.',
      evidence: ['گزارش توقف ۰۶:۴۰', 'ظرفیت جایگزین پرس ۱ محدود به ۷۰٪', 'برنامه بچ BATCH-2418'],
      recommendation: 'تایید فوری BR-MNT-442 و انتقال بچ اولویت‌دار SO-3092 به پرس ۱.',
      period: 'امروز',
      impact: 'ریسک جریمه تاخیر و از دست رفتن اعتبار OEM',
      confidence: 'بالا',
      recordType: 'transaction',
      recordId: 'BR-MNT-442',
      workId: 'work-maint-1',
    },
    {
      id: 'ins-3',
      title: 'خرید اضطراری مواد اصطکاکی به الگوی تکرارشونده تبدیل شده',
      category: 'ریسک تامین',
      severity: 'warning',
      summary: 'دو خرید اضطراری در ده روز و ۱۹٪ افزایش هزینه حمل نشان می‌دهد نقطه سفارش با مصرف واقعی هماهنگ نیست.',
      evidence: ['BR-MR-184 و سفارش اضطراری ۸ مرداد', 'بارنامه حمل #۷۷۱', 'مصرف میانگین ۶ کیسه در روز'],
      recommendation: 'افزایش نقطه سفارش به ۴۵ کیسه و بستن قرارداد تامین ماهانه با شیمی پلیمر کاوه.',
      period: '۱۰ روز اخیر',
      impact: 'کاهش هزینه حمل و ریسک توقف اختلاط',
      confidence: 'متوسط',
      recordType: 'purchase',
      recordId: 'BR-MR-184',
      workId: 'work-wh-1',
    },
    {
      id: 'ins-4',
      title: 'تحویل به‌موقع با تخصیص زودهنگام محصول نهایی بهبود می‌یابد',
      category: 'فروش',
      severity: 'info',
      summary: 'در ۳۰ روز اخیر ۷۰٪ تاخیرها از تخصیص دیرهنگام موجودی FG به سفارش‌ها ناشی شده، نه از کمبود ظرفیت تولید.',
      evidence: ['سوابق SO-3061 تا SO-3092', 'موجودی FG-8842 در زمان تخصیص', 'زمان صدور محموله‌های SH-*'],
      recommendation: 'تخصیص موجودی در لحظه ثبت سفارش و هشدار خودکار هنگام افت پوشش زیر ۱۰ روز.',
      period: '۳۰ روز اخیر',
      impact: 'بهبود ۴ واحدی نرخ تحویل به‌موقع',
      confidence: 'متوسط',
      recordType: 'inventory',
      recordId: 'inv-fg-8842',
      workId: 'work-re-1',
    },
  ],
  calendarEvents: [
    { id: 'cal-1', title: 'جلسه برنامه‌ریزی تولید هفته', time: '۱۰:۰۰', date: 'امروز', type: 'مدیریتی', workId: 'work-plan-1', unitId: 'unit-plan' },
    { id: 'cal-2', title: 'کمیته کیفیت — بررسی بچ BATCH-2417', time: '۱۲:۳۰', date: 'امروز', type: 'کیفیت', workId: 'work-qc-1', unitId: 'unit-agri' },
    { id: 'cal-3', title: 'بازبینی وضعیت تعمیر پرس ۲', time: '۱۵:۰۰', date: 'امروز', type: 'نگهداری', workId: 'work-maint-1', unitId: 'unit-hr' },
    { id: 'cal-4', title: 'بارگیری محموله SH-1207', time: '۰۷:۳۰', date: 'فردا', type: 'ارسال', workId: 'work-ship-1', unitId: 'unit-re' },
    { id: 'cal-5', title: 'مهلت پاسخ نامه ۴۱۲/ک', time: '۱۲:۰۰', date: 'آتی', type: 'مکاتبات', workId: 'work-corr-1', unitId: 'unit-corr' },
    { id: 'cal-6', title: 'بازبینی بهای تمام‌شده بچ', time: '۱۱:۰۰', date: 'آتی', type: 'مالی', unitId: 'unit-fin' },
  ],
  activityFeed: [
    { id: 'act-1', time: '۰۹:۲۰', text: 'بچ BATCH-2418 وارد کوره پخت شد؛ زمان ترخیص تخمینی ۲۰ مرداد.', unit: 'تولید' },
    { id: 'act-2', time: '۰۹:۱۰', text: 'کسری ۶۴۰ جفت FG-8842 برای سفارش SO-3092 اعلام شد.', unit: 'فروش', recordType: 'inventory', recordId: 'inv-fg-8842' },
    { id: 'act-3', time: '۰۸:۴۵', text: 'بارگیری محموله SH-1207 برای مشتری بازار یدکی آغاز شد.', unit: 'انبار محصول' },
    { id: 'act-4', time: '۰۸:۱۵', text: 'BR-MR-184 برای ماده اصطکاکی ثبت و به کارتابل تایید ارسال شد.', unit: 'تدارکات', recordType: 'purchase', recordId: 'BR-MR-184' },
    { id: 'act-5', time: '۰۷:۲۰', text: 'برگه قرنطینه QC-0241 برای بچ BATCH-2417 صادر شد.', unit: 'کیفیت', recordType: 'work', recordId: 'work-qc-1' },
    { id: 'act-6', time: '۰۶:۴۵', text: 'توقف پرس هیدرولیک ۲ به دلیل نشتی ثبت شد.', unit: 'نگهداری', recordType: 'work', recordId: 'work-maint-1' },
  ],
  productionOrders: [
    {
      id: 'PROD-1148',
      soId: 'SO-3092',
      itemSku: 'FG-8842 — لنت دیسکی سواری',
      quantity: 2400,
      unit: 'جفت',
      stage: 'hold',
      press: 'پرس ۲',
      batchIds: ['BATCH-2417', 'BATCH-2418'],
      dueDate: '۲۰ مرداد',
      status: 'danger',
      blocker: 'پرس ۲ متوقف و بچ BATCH-2417 قرنطینه شد؛ بدون بچ جایگزین، تعهد تحویل SO-3092 محقق نمی‌شود.',
      materialBlockerIds: ['inv-oil-10w40'],
      workId: 'work-re-1',
    },
    {
      id: 'PROD-1147',
      itemSku: 'FG-8842 — لنت دیسکی سواری',
      quantity: 1600,
      unit: 'جفت',
      stage: 'materials',
      batchIds: [],
      dueDate: '۲۲ مرداد',
      status: 'warning',
      blocker: 'کمبود رزین فنولیک SP-1068 — منتظر تایید BR-MR-184.',
      materialBlockerIds: ['inv-oil-10w40'],
      workId: 'work-wh-1',
    },
    {
      id: 'PROD-1145',
      itemSku: 'FG-8845 — لنت دیسکی شاسی‌بلند',
      quantity: 1800,
      unit: 'جفت',
      stage: 'production',
      press: 'پرس ۱',
      batchIds: ['BATCH-2419'],
      dueDate: '۲۱ مرداد',
      status: 'warning',
      blocker: 'خط پرداخت منتظر رنگ پودری اپوکسی — BR-MR-191.',
      materialBlockerIds: ['inv-powder'],
      workId: 'work-fuel-1',
    },
    {
      id: 'PROD-1146',
      itemSku: 'FG-8840 — لنت دیسکی وانتی',
      quantity: 2200,
      unit: 'جفت',
      stage: 'qc',
      press: 'پرس ۱',
      batchIds: ['BATCH-2416'],
      dueDate: '۱۹ مرداد',
      status: 'success',
    },
    {
      id: 'PROD-1143',
      itemSku: 'FG-8838 — لنت دیسکی سواری اقتصادی',
      quantity: 2000,
      unit: 'جفت',
      stage: 'finished_goods',
      press: 'پرس ۱',
      batchIds: ['BATCH-2412'],
      dueDate: '۱۸ مرداد',
      status: 'success',
    },
    {
      id: 'PROD-1142',
      itemSku: 'FG-8836 — لنت دیسکی سبک تجاری',
      quantity: 1700,
      unit: 'جفت',
      stage: 'planning',
      batchIds: [],
      dueDate: '۲۴ مرداد',
      status: 'info',
    },
    {
      id: 'PROD-1141',
      itemSku: 'FG-8835 — لنت دیسکی وانتی سنگین',
      quantity: 1500,
      unit: 'جفت',
      stage: 'shipment',
      press: 'پرس ۲',
      batchIds: ['BATCH-2408'],
      dueDate: '۱۷ مرداد',
      status: 'success',
    },
  ],
  productionBatches: [
    {
      id: 'BATCH-2417',
      productionOrderId: 'PROD-1148',
      press: 'پرس ۲',
      stage: 'کنترل کیفیت',
      qcStatus: 'quarantined',
      qcRecordId: 'QC-0241',
      quantity: 980,
      unit: 'کیلوگرم',
      startedAt: '۱۷ مرداد',
      note: 'ضریب اصطکاک نمونه خارج از پنجره مجاز؛ با برگه QC-0241 قرنطینه شد.',
      workId: 'work-qc-1',
    },
    {
      id: 'BATCH-2418',
      productionOrderId: 'PROD-1148',
      press: 'پرس ۱',
      stage: 'کوره پخت',
      qcStatus: 'pending',
      quantity: 3200,
      unit: 'جفت',
      startedAt: '۱۸ مرداد',
      note: 'در کوره پخت؛ اگر پرس ۲ امشب راه بیفتد، ترخیص QC روز ۲۰ مرداد ممکن است.',
      workId: 'work-fuel-1',
    },
    {
      id: 'BATCH-2419',
      productionOrderId: 'PROD-1145',
      press: 'پرس ۱',
      stage: 'پرس گرم',
      qcStatus: 'pending',
      quantity: 2800,
      unit: 'جفت',
      startedAt: '۱۸ مرداد',
      note: 'شارژ میکسر کامل؛ خط پرداخت منتظر رنگ پودری اپوکسی است.',
      workId: 'work-fuel-1',
    },
    {
      id: 'BATCH-2416',
      productionOrderId: 'PROD-1146',
      press: 'پرس ۱',
      stage: 'کنترل کیفیت',
      qcStatus: 'passed',
      qcRecordId: 'QC-0238',
      quantity: 2600,
      unit: 'جفت',
      startedAt: '۱۷ مرداد',
      note: 'ترخیص QC انجام شد؛ به انبار محصول نهایی FG-8842 وارد شد.',
    },
    {
      id: 'BATCH-2412',
      productionOrderId: 'PROD-1143',
      press: 'پرس ۱',
      stage: 'محصول نهایی',
      qcStatus: 'passed',
      quantity: 2000,
      unit: 'جفت',
      startedAt: '۱۵ مرداد',
      note: 'ترخیص و بسته‌بندی کامل؛ آماده ارسال.',
    },
    {
      id: 'BATCH-2408',
      productionOrderId: 'PROD-1141',
      press: 'پرس ۲',
      stage: 'ارسال',
      qcStatus: 'passed',
      quantity: 1500,
      unit: 'جفت',
      startedAt: '۱۳ مرداد',
      note: 'در محموله SH-1201 برای بازار یدکی ارسال شد.',
    },
  ],
  settlements: [
    {
      id: 'STL-701',
      agentName: 'پیمانکار تعمیرات هیدرولیک صنعت‌کار',
      unitId: 'unit-hr',
      unitLabel: 'نگهداری و تعمیرات',
      task: 'تعویض شیر و آب‌بندی جک اصلی پرس هیدرولیک ۲',
      assignedDate: '۱۷ مرداد',
      dueDate: '۱۹ مرداد',
      completion: 'تعمیر در حال انجام؛ منتظر قطعه یدکی',
      evidence: 'گزارش بازدید فنی + فاکتور پیمانکار #۵۵۲۱',
      confirmation: 'وابسته به تایید هزینه BR-MNT-442',
      approvedAmount: 320,
      paidAmount: 0,
      outstandingAmount: 320,
      status: 'pending_confirmation',
      workId: 'work-maint-1',
    },
    {
      id: 'STL-706',
      agentName: 'شرکت حمل و نقل رخش‌بار',
      unitId: 'unit-fin',
      unitLabel: 'مالی',
      task: 'حمل اضطراری مواد اولیه از تامین‌کننده کاوه',
      assignedDate: '۱۶ مرداد',
      dueDate: '۱۸ مرداد',
      completion: 'تکمیل و رسید تحویل ثبت شد',
      evidence: 'بارنامه حمل #۷۷۱',
      confirmation: 'در انتظار تایید مدیر مالی',
      approvedAmount: 58,
      paidAmount: 0,
      outstandingAmount: 58,
      status: 'submitted',
      workId: 'work-fin-2',
    },
    {
      id: 'STL-709',
      agentName: 'پیمانکار بسته‌بندی و بارگیری انبار محصول',
      unitId: 'unit-wh',
      unitLabel: 'انبار مواد و محصول',
      task: 'بسته‌بندی و بارگیری محموله SH-1207 برای بازار یدکی',
      assignedDate: '۱۷ مرداد',
      dueDate: '۱۸ مرداد',
      completion: 'بارگیری تکمیل شد',
      evidence: 'حواله خروج + عکس بارگیری',
      confirmation: 'تایید سرپرست انبار',
      approvedAmount: 46,
      paidAmount: 0,
      outstandingAmount: 46,
      status: 'ready_for_settlement',
      workId: 'work-re-1',
    },
    {
      id: 'STL-712',
      agentName: 'آزمایشگاه برون‌سپاری تست NVH پارسیان',
      unitId: 'unit-agri',
      unitLabel: 'کنترل کیفیت',
      task: 'آزمون تکمیلی NVH نمونه بچ BATCH-2416',
      assignedDate: '۱۴ مرداد',
      dueDate: '۱۷ مرداد',
      completion: 'گزارش آزمون تایید و بایگانی شد',
      evidence: 'گزارش آزمایشگاه NVH-118',
      confirmation: 'تایید شده',
      approvedAmount: 24,
      paidAmount: 24,
      outstandingAmount: 0,
      status: 'settled',
      workId: 'work-qc-1',
    },
    {
      id: 'STL-715',
      agentName: 'پیمانکار نظافت صنعتی و HSE بهاران',
      unitId: 'unit-hr',
      unitLabel: 'نگهداری و تعمیرات',
      task: 'نظافت عمقی و بازرسی HSE سالن پرس پس از تعمیر',
      assignedDate: '۱۸ مرداد',
      dueDate: '۱۹ مرداد',
      completion: 'گزارش تصویری ناقص ارسال شده',
      evidence: 'چک‌لیست HSE',
      confirmation: 'نیاز به گزارش تصویری تکمیلی',
      approvedAmount: 12,
      paidAmount: 0,
      outstandingAmount: 12,
      status: 'needs_rework',
      workId: 'work-maint-1',
    },
  ],
}

/** Expand work list for table density while keeping core scenario IDs intact */
export function withExpandedWork(state: DemoState): DemoState {
  if (state.workItems.length >= 18) return state
  const extras = Array.from({ length: 12 }).map((_, i) => {
    const n = i + 1
    return {
      id: `work-aux-${n}`,
      title: [
        'کالیبراسیون ترموکوپل کوره پخت',
        'شمارش دوره‌ای مواد اولیه انبار',
        'پیگیری فاکتور تامین‌کننده رزین',
        'آماده‌سازی گزارش تولید هفتگی',
        'بازرسی قالب‌های پرس ۱',
        'به‌روزرسانی پرونده مشتری OEM',
        'ممیزی برگه‌های ثبت بچ',
        'بایگانی گواهی آزمون بچ BATCH-2416',
        'بازبینی سقف تایید خرید مواد',
        'سرویس دوره‌ای میکسر شماره ۳',
        'کنترل حواله خروج محصول نهایی',
        'تسویه پیمانکار نگهداری هیدرولیک',
      ][i],
      type: ['کیفیت', 'انبار', 'مالی', 'مدیریتی', 'نگهداری', 'فروش', 'کیفیت', 'مکاتبه', 'مالی', 'نگهداری', 'انبار', 'مالی'][i],
      stage: (['آماده‌سازی', 'در حال اجرا', 'مجاز', 'مشاهده', 'پیشنهاد', 'آماده‌سازی', 'در حال اجرا', 'نتیجه', 'مجاز', 'در حال اجرا', 'آماده‌سازی', 'مشاهده'] as const)[i],
      owner: ['عامل کنترل کیفیت', 'عامل انبار', 'عامل مالی', 'عامل برنامه‌ریزی', 'عامل نگهداری', 'عامل فروش', 'عامل کنترل کیفیت', 'عامل مکاتبات', 'عامل مالی', 'عامل نگهداری', 'عامل انبار', 'عامل مالی'][i],
      unitId: ['unit-agri', 'unit-wh', 'unit-fin', 'unit-plan', 'unit-hr', 'unit-re', 'unit-agri', 'unit-corr', 'unit-fin', 'unit-hr', 'unit-wh', 'unit-fin'][i],
      priority: (['medium', 'low', 'medium', 'high', 'medium', 'medium', 'low', 'low', 'medium', 'medium', 'low', 'high'] as const)[i],
      updated: '۰۸:۰۰',
      description: 'کار عملیاتی تکمیلی برای زنده بودن کارتابل دمو.',
      linked: [] as string[],
    }
  })
  return { ...state, workItems: [...state.workItems, ...extras] }
}
